### ISSUE TITLE
scripts/train.sh: 18: Syntax error: word unexpected (expecting "in")

### ISSUE THREAD

**Issue by RauchLukas** [Pointcept/Pointcept#100]
Hi community, 

I am new to Pointcept and wish to use this Repo in the future for my research in the fields of Point Cloud Segmentation. 
Future ME _probably_ wants to implement a new open source dataset. 

However, for now, I am tinkering around to get the package running in a Docker container. It looks like the Docker setup works, but if I run the  ```/srcipts/train.sh``` script, bash complained about Syntax error: 

```bash
root@ab45ce7e370e:/home/Pointcept# sh scripts/train.sh -p python -d s3dis -c semseg-pt-v2m2-0-base -n semseg-pt-v2m2-0-base
: not foundin.sh: 2:
: not foundin.sh: 6:
: not foundin.sh: 8:
: not foundin.sh: 15:
: not foundin.sh: 16:
scripts/train.sh: 18: Syntax error: word unexpected (expecting "in")
```

Can someone help with this ERROR? 
From my understanding, this should be due to bad `opts` parsing. But the options `-p -d -c -n` in this particular order seem right to me. 

Thanks in advance, 
Lukas

**Comment by Gofinge** [comment]
How about try this: https://stackoverflow.com/questions/26671815/not-foundsh-2-error-comes-while-exectutin-a-shell-command ?

**Comment by RauchLukas** [comment]
> How about try this: https://stackoverflow.com/questions/26671815/not-foundsh-2-error-comes-while-exectutin-a-shell-command ?

Thanks for fast response. 
I could not get it running with the train.sh script. Not sure if this is due to the fact that I am deploying on an ubuntu 22.04 build. 
However, running the training directly from the `train.py` works just fine.

**Comment by Gofinge** [comment]
Hi, maybe you can try this: "sed -i 's/\r$//' scripts/train.sh"

**Comment by RauchLukas** [comment]
Thank you again! This fixed it.
