### ISSUE TITLE
Any plan to support some latest Instance Segmentation method

### ISSUE THREAD

**Issue by RayYoh** [Pointcept/Pointcept#107]
Dear authors,

This repo is very useful. However, I would like to ask whether there are any plans to support some of the latest point cloud instance segmentation algorithms (like [Mask3D](https://github.com/JonasSchult/Mask3D), and [SPFormer](https://github.com/sunjiahao1999/SPFormer)). 

Best,
Ray

**Comment by Gofinge** [comment]
Hi, I used to consider adding support to Mask3D and we do have one unpublished version which supports this work. While Mask3D relies on an over-segmentation method which can be viewed as a ground-truth method adopted by ScanNet annotation (leading to a high performance), I decided not to introduce this to our framework. I have not checked whether SPFormer adopts a similar strategy, maybe when I have some time I will check it. Also, contribution from the community is welcome!!

**Comment by RayYoh** [comment]
Hi, thanks for your reply. SPFormer used a similar strategy; they used super points. A new work named [Oneformer3D](https://github.com/filaPro/oneformer3d) is also based on the super points. Indeed, unlike Pointcept, they all introduced additional info from the dataset. May I ask if it is possible to get your unpublished Mask3D code? 
BTW, I'd like to ask whether there are any differences between GridSample (in transform.py) and voxel (used in pointgroupops)?

**Comment by Gofinge** [comment]
> Hi, thanks for your reply. SPFormer used a similar strategy; they used super points. A new work named [Oneformer3D](https://github.com/filaPro/oneformer3d) is also based on the super points. Indeed, unlike Pointcept, they all introduced additional info from the dataset. May I ask if it is possible to get your unpublished Mask3D code? BTW, I'd like to ask whether there are any differences between GridSample (in transform.py) and voxel (used in pointgroupops)?

I renamed GridSample from Voxelization (actually from Chrischoy MinkUNet) as I think the grid sample is a more proper description. As point-based methods also need grid sampling instead of voxelization. Actually, there is no foundational difference between voxel and point.

According to our implementation of Mask3D, we did not add the super points information. If you are still interested in our unpublished implementation, you can contact me with email and I will try to find the code.
