### ISSUE TITLE
Scalar Attention implementation

### ISSUE THREAD

**Issue by EricLina** [Pointcept/Pointcept#11]
Theoretically Vector Attention seems to have much more computational complexity than Scalar Attention because the weights between channels have been learned in vector attention.

**I'm wondering if there is an implementation of Sparse Scalar Attention(Normal attention) operator in this repository**? (Matrix multiplication may not be very efficient.) 

And the paper Point Transformer V2 mentioned that Scalar Attention is a special case of Vector Attention, do you have any suggestions on how to modify Vector Attention to Scalar attention?

**Comment by Gofinge** [comment]
For classical dot-product attention (scalar attention):
1. Change the `subtraction` relation to the `multiply` relation.
2. Change the learnable Weight Encoding layer to `Sum` weight encoding.
3. Add softmax & Scaler of attention weight.

For multi-head dot-product attention (MSA), you can modify the grouped linear to an unlearnable layer and make it function as a grouped sum. The rest modifications are the same as scalar attention.
