### ISSUE TITLE
Question about data augmentation

### ISSUE THREAD

**Issue by RayYoh** [Pointcept/Pointcept#110]
Hi, Xiaoyang. Recently, I have successfully reproduced Mask3D based on your provided code, and I am trying to understand some components of this repo. I find that there are usually twice CenterShift (one for apply_z and one not) in most of the default config files. I'd like to ask if there are any necessary reasons for this setting or it is just one trick to get better performance.

Also, before I trained Mask3D, I trained PointGroup using the provided default config file, and everything went well. But when I used the latest `InsSegEvaluator`, I found that the metrics were always near 0 (I also used the old version of InsSegEvaluator, and it works well). I think there may be some problems with the code (a little bit confused, caz it is ok for PointGroup). Maybe some of the contributors can double-check it since the new version is a little different from the old one (the old one is more similar to the ScanNet provided).

During my experiments, I found that the logger records every iteration of information and evaluates after every epoch. Although it is more detailed, I think you may consider adding the interval param (something like openmmlab's codes), which is more user-friendly.

Hope everything goes well.

Best,
Lei

**Comment by Gofinge** [comment]
```
 I find that there are usually twice CenterShift (one for apply_z and one not) in most of the default config files. 
```
Hi, this is just my intuitive choice without a careful ablation as it is a minor point. You can try one operate one CenterShift. (Dual shift is introduced to center point cloud after cropping)

```
Also, before I trained Mask3D, I trained PointGroup using the provided default config file, and everything went well. But when I used the latest InsSegEvaluator, I found that the metrics were always near 0 (I also used the old version of InsSegEvaluator, and it works well).
```
The two versions of codes are quite different, we don't suggest directly using InsSegEvaluator from a new version to an old version without a careful check.

**Comment by RayYoh** [comment]
Got that. Thank you.
