### ISSUE TITLE
ModuleNotFoundError: No module named 'pointgroup_ops'

### ISSUE THREAD

**Issue by hpc100** [Pointcept/Pointcept#122]
Thank you for your great work !

When I tried to run somme pointcept code I get the error below from the code named point_group_v1m1_base.py :

`from pointgroup_ops import ballquery_batch_p, bfs_cluster`
`ModuleNotFoundError: No module named 'pointgroup_ops'`

I tried to run these commands, but this don't work : 
- cd Pointcept/libs
- cd pointgroups_ops
- python setup.py install 

Thank's in advance.

**Comment by darissa** [comment]
Hi @hpc100. I face the same error. But I noticed this error has been issued, but still no solution.

**Comment by Gofinge** [comment]
Hi, check README [here](https://github.com/Pointcept/Pointcept?tab=readme-ov-file#pointgroup). It can not be installed by simply `python setup.py install`.

**Comment by hpc100** [comment]
Thank's for the link. It works well !
