### ISSUE TITLE
how to get 'offset' parameter for a custom point cloud data

### ISSUE THREAD

**Issue by JackMa-coder** [Pointcept/Pointcept#13]
Hi, thanks for the great work. I'm trying to use Point Transformer to handle custom point clouds from depth maps and I'm getting confused about input_dict["offset"] at [here](https://github.com/Pointcept/Pointcept/blob/ea10c880815e89dd294ddfbb1ba2013201d73baa/pointcept/models/point_transformer/point_transformer_seg.py#L196) , do I need to generate  the  'offset' parameter for a custom point cloud data and how to calculate the 'offset' from the point cloud data?
Looking forward to your response

**Comment by Gofinge** [comment]
Hi, an illustration is available [here](https://github.com/Pointcept/Pointcept#offset) and [here](https://github.com/Pointcept/Pointcept/blob/main/configs/scannet/semseg-pt-v2m2-2-precise-evaluate.py#L117) is an example how to generate custom offset during transform.

**Comment by JackMa-coder** [comment]
> Hi, an illustration is available [here](https://github.com/Pointcept/Pointcept#offset) and [here](https://github.com/Pointcept/Pointcept/blob/main/configs/scannet/semseg-pt-v2m2-2-precise-evaluate.py#L117) is an example how to generate custom offset during transform.

Thank you for your reply. By the way, can this follwing codes verify whether this project corrected installed? If not, how can I verify it simply？Thank you.
``` python
bs = 4
    npts = 128
    len_xyz = 3
    feat_dims = 6
    num_classes = 23
    coord = torch.rand(bs,npts, len_xyz).cuda()
    feat = torch.rand(bs,npts, feat_dims).cuda()
    offset = [npts, npts, npts, npts]
    offset = torch.tensor(offset).cuda()
    pointTransformer = PointTransformerV2(in_channels = feat_dims, 
                                          num_classes=num_classes).to(offset.device)
    print(
        "model parameters:", sum(param.numel() for param in pointTransformer.parameters())
    )

    data_dict = dict(
        coord = coord,
        feat = feat,
        offset = offset
    )
    result = pointTransformer(data_dict)
    print("test result", result)
```

**Comment by Gofinge** [comment]
Kindly remind that in Pointcept, `bs` and `npts` share the same channel, so reshape coord and feat as `[bs * npts, len_xyz]`, also the offset for your demo should be `[npts, 2*npts, 3*npts, 4*npts]`

**Comment by JackMa-coder** [comment]
> Kindly remind that in Pointcept, `bs` and `npts` share the same channel, so reshape coord and feat as `[bs * npts, len_xyz]`, also the offset for your demo should be `[npts, 2*npts, 3*npts, 4*npts]`

Thank you for your Immediate reply and your great work. It does works.
