### ISSUE TITLE
How to understand the Contrastive Loss in Paper Masked Scene Contrast?

### ISSUE THREAD

**Issue by Lazzzycoding** [Pointcept/Pointcept#132]
Dear authors @yxlao @blueeaglex @eltociear @wcy1122 @Gofinge 

How to understand the contrastive loss (in 4.1 Contrastive Target) added upon the matched points, especially the similarity matrix? Is the pairwise cosine similarity matrix between positive samples and negative samples representing semantic or category information? 

Thanks a lot.

**Comment by Gofinge** [comment]
Hi, code here denotes the implementation of the contrastive target (InfoNCELoss): https://github.com/Pointcept/Pointcept/blob/main/pointcept/models/masked_scene_contrast/masked_scene_contrast_v1m1_base.py#L174-L203

It can be trivially understood as applying cross entropy to the pair-wise similarity of the sample pair. The "classification" target is positive pairs of samples.

**Comment by Lazzzycoding** [comment]
> Hi, code here denotes the implementation of the contrastive target (InfoNCELoss): https://github.com/Pointcept/Pointcept/blob/main/pointcept/models/masked_scene_contrast/masked_scene_contrast_v1m1_base.py#L174-L203
> 
> It can be trivially understood as applying cross entropy to the pair-wise similarity of the sample pair. The "classification" target is positive pairs of samples.

Hi, 
   Thanks for your kind reply. The reason that I asked the semantic information of the contrastive loss in Masked Scene Contrast is that I recently read a paper about using multi-class information in contrastive loss. But this paper is about object detection, and the paper is CoIn: Contrastive Instance Feature Mining for Outdoor 3D Object Detection with Very Limited Annotations. The MCcont loss uses the reference matrix to consider the multiple category information. So, how about the category information in the similarity matrix in contrastive loss in the Masked Scene Contrast? 

Thanks a lot.

**Comment by Gofinge** [comment]
In fact, many losses in 3D contrastive learning are fundamentally InfoNCELoss (Similarity Matrix + CE Loss, https://arxiv.org/pdf/1807.03748.pdf). Usually, some papers introduce it with a different name to distinguish different targets that apply InfoNCELoss (e.g. point, object, segment ...). I have not read the paper you mentioned carefully, but I think it might be a similar case as I just described.

**Comment by whuhxb** [comment]
> In fact, many losses in 3D contrastive learning are fundamentally InfoNCELoss (Similarity Matrix + CE Loss, https://arxiv.org/pdf/1807.03748.pdf). Usually, some papers introduce it with a different name to distinguish different targets that apply InfoNCELoss (e.g. point, object, segment ...). I have not read the paper you mentioned carefully, but I think it might be a similar case as I just described.

The mentioned paper emphasizes that the proposed Loss is mainly for multi-class contrastive learning loss, which considers category information. I want to borrow the multi-class idea into your paper. So, I wonder to know how you construct the similarity matrix, have you considered the category or semantic information in the similarity matrix?

**Comment by Gofinge** [comment]
> > In fact, many losses in 3D contrastive learning are fundamentally InfoNCELoss (Similarity Matrix + CE Loss, https://arxiv.org/pdf/1807.03748.pdf). Usually, some papers introduce it with a different name to distinguish different targets that apply InfoNCELoss (e.g. point, object, segment ...). I have not read the paper you mentioned carefully, but I think it might be a similar case as I just described.
> 
> Hi, do you have other suggestion papers on improving the InfoNCE loss?

Simple is more. InfoNCELoss is effective enough for a contrastive learning setting and not the bottleneck.

**Comment by whuhxb** [comment]
> > > In fact, many losses in 3D contrastive learning are fundamentally InfoNCELoss (Similarity Matrix + CE Loss, https://arxiv.org/pdf/1807.03748.pdf). Usually, some papers introduce it with a different name to distinguish different targets that apply InfoNCELoss (e.g. point, object, segment ...). I have not read the paper you mentioned carefully, but I think it might be a similar case as I just described.
> > 
> > 
> > Hi, do you have other suggestion papers on improving the InfoNCE loss?
> 
> Simple is more. InfoNCELoss is effective enough for a contrastive learning setting and not the bottleneck.

Thanks. Do you have other suggestions on improving contrastive learning on masked scene contrast?

**Comment by whuhxb** [comment]
> > > In fact, many losses in 3D contrastive learning are fundamentally InfoNCELoss (Similarity Matrix + CE Loss, https://arxiv.org/pdf/1807.03748.pdf). Usually, some papers introduce it with a different name to distinguish different targets that apply InfoNCELoss (e.g. point, object, segment ...). I have not read the paper you mentioned carefully, but I think it might be a similar case as I just described.
> > 
> > 
> > The mentioned paper emphasizes that the proposed Loss is mainly for multi-class contrastive learning loss, which considers category information from instance features. I want to borrow the multi-class idea into the contrastive loss in your paper to improve performance. Is the contrastive loss in your paper for calculating semantic segmentation? So, I wonder to know how you construct the similarity matrix, have you considered the category or semantic information in the similarity matrix?
> 
> Not related to semantic segmentation, the InfoNCE makes the feature (representation) of positive point pairs more similar and the feature of negative point pairs more different.

Without semantic or category information in the contrastive loss in Masked Scene Contrast, how to relate the contrastive learning with semantic segmentation task? In my view, the contrastive loss helps the semantic segmentation task. Is it right?

**Comment by Lazzzycoding** [comment]
I have read PointContrast, Contrastive Scene Context, and your paper, and all these papers focus on the view image to conduct contrastive learning like 2D image. Have you ever met some papers about point-level contrastive learning applied in full supervision 3D semantic segmentation?

**Comment by Gofinge** [comment]
I have not seen any paper related to point-level contrastive learning applied in full supervision 3D semantic segmentation. It sounds like the challenge is huge data noise exists in point cloud data and insufficient data (ScanNet), which might be resulting in a problem in convergence.

**Comment by Lazzzycoding** [comment]
> I have not seen any paper related to point-level contrastive learning applied in full supervision 3D semantic segmentation. It sounds like the challenge is huge data noise exists in point cloud data and insufficient data (ScanNet), which might be resulting in a problem in convergence.

In the overall loss of Masked Scene Contrast, the total loss are InfoNCE loss, normal loss, and color loss. In other point cloud papers, usually normal are compared with curve, is the curve equal to surfel here? Or could the curve further help improve the current baseline? Do you have some suggestions? Thanks a lot.
