### ISSUE TITLE
The receptive field Visualization

### ISSUE THREAD

**Issue by EricLina** [Pointcept/Pointcept#14]
Hello!
PointCept is a great tool. Can you add a module for visualization? Especially about the receptive field that I've seen many times in your paper.

If it's convenient, can you share the code about ERF(Effective receptive field) here?

**Comment by Gofinge** [comment]
Hi, a basic visualization module is available [here](https://github.com/Pointcept/Pointcept/blob/main/pointcept/utils/visualization.py#L21), and usually, I save the point cloud as ply, then further visualize in Meshlab. Also, thanks for your kind advice, we will try to enhance the visualization module in the next version.

**Comment by EricLina** [comment]
> Hi, a basic visualization module is available [here](https://github.com/Pointcept/Pointcept/blob/main/pointcept/utils/visualization.py#L21), and usually, I save the point cloud as ply, then further visualize in Meshlab. Also, thanks for your kind advice, we will try to enhance the visualization module in the next version.

Thank you.
