### ISSUE TITLE
KITTI config PvTv3

### ISSUE THREAD

**Issue by L-Reichardt** [Pointcept/Pointcept#140]
Hello,
when will the PvTv3 config for KITTI be released?
I am currently writing a paper and would like to feature PvTv3 as a baseline network in the evaluations.

Best Regards,
L

**Comment by Gofinge** [comment]
Soon, just finished the rebuttal, currently working on it!!

**Comment by L-Reichardt** [comment]
@Gofinge Ok thank you for your update. Yes SemanticKITTI. I will check in regularly,

**Comment by sunnyheart008205** [comment]
@Gofinge Could you please provide semantickitti config for PTv3? Thanks

**Comment by Gofinge** [comment]
Hi, forgive me, our team member is interested in the Waymo 2024 challenge, so we have to delay the release of configs for outdoor semantic segmentation. Yet, to be honest, these configs can be easily reproduced when referring to our configs for indoor multi-dataset training and configs for semanticKITTI + PTv2.

**Comment by sunnyheart008205** [comment]
OK, I will try, thanks



---- Replied Message ----
| From | Xiaoyang ***@***.***> |
| Date | 03/19/2024 14:26 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Pointcept/Pointcept] KITTI config PvTv3 (Issue #140) |

Hi, forgive me, our team member is interested in the Waymo 2024 challenge, so we have to delay the release of configs for outdoor semantic segmentation. Yet, to be honest, these configs can be easily reproduced when referring to our configs for indoor multi-dataset training and configs for semanticKITTI + PTv2.
