### ISSUE TITLE
Specific Code Release Time

### ISSUE THREAD

**Issue by JiachengDeng** [Pointcept/Pointcept#15]
I have recently read **_Masked Scene Contrast_** and am fascinated by it. And I would like to learn more about the code implementation of the method. So I took the liberty of asking if it would be convenient to provide a specific code release time?

**Comment by Gofinge** [comment]
Hi, Thanks for being interested in our work, and the code will be released in early June.

**Comment by JiachengDeng** [comment]
Thx! Looking forward to it!
