### ISSUE TITLE
    class OctreeT(Octree): TypeError: NoneType takes no arguments

### ISSUE THREAD

**Issue by jc991206** [Pointcept/Pointcept#150]
File "/home/jichao/jc/code/Pointcept-main/pointcept/models/octformer/octformer_v1m1_base.py", line 32, in <module>
    class OctreeT(Octree):
TypeError: NoneType takes no arguments
配置完环境之后显示 octree没定义 老哥们，这个该怎么解决

**Comment by Gofinge** [comment]
hello, v1.5.1 修复了，你update下，或者手动看下我对octformer模型文件的修改？

**Comment by Gofinge** [comment]
如果就是v1.5.1的问题的话，安装一下octree的额外依赖就好了，我晚点再看看

**Comment by jc991206** [comment]
> > 如果就是v1.5.1的问题的话，安装一下octree的额外依赖就好了，我晚点再看看
> 
> 很抱歉打扰您，我又尝试了v1.5.1，报错了相同的错误 File "/home/jichao/jc/code/Pointcept-1.5.1/exp/s3dis/semseg-pt-v3m1-0-rpe/code/pointcept/models/octformer/octformer_v1m1_base.py", line 32, in class OctreeT(Octree): TypeError: NoneType takes no arguments

**Comment by Gofinge** [comment]
I shift to English for any other who wants to refer the issue. So, the issue can be solved by install addition requirement for octformer (refer here https://github.com/Pointcept/Pointcept?tab=readme-ov-file#octformer). And I will try to fix it soon.

**Comment by mellody11** [comment]
> I shift to English for any other who wants to refer the issue. So, the issue can be solved by install addition requirement for octformer (refer here https://github.com/Pointcept/Pointcept?tab=readme-ov-file#octformer). And I will try to fix it soon.

Has the problem been resolved? It is still report error now. Thanks.

**Comment by Gofinge** [comment]
Hi, I fixed the issue with the following commit (https://github.com/Pointcept/Pointcept/commit/247b621bdff6245ce36da3b1e683a118e67217be), hope you guys enjoy the codebase.

**Comment by jc991206** [comment]
> > I shift to English for any other who wants to refer the issue. So, the issue can be solved by install addition requirement for octformer (refer here https://github.com/Pointcept/Pointcept?tab=readme-ov-file#octformer). And I will try to fix it soon.
> 
> Has the problem been resolved? It still report error now and also happend in v1.5.1. Thanks.

It can be successful after installing octree according to the author's method
