### ISSUE TITLE
valueerror:multidatasettrainer:onecyclelr:expected positive integer total_steps，but got 0

### ISSUE THREAD

**Issue by hfutdzx** [Pointcept/Pointcept#153]
encountered this error message:

valueerror:multidatasettrainer:onecyclelr:expected positive integer total_steps，but got 0

may i ask if there is an issue with the torch version（1.13.1） or other reasons？

**Comment by Gofinge** [comment]
Hi, please check the data path, this is usually caused because DataLoader fails to find any data in the specific data path.

**Comment by hfutdzx** [comment]
thanks！
