### ISSUE TITLE
typeerror:’Point’ object is not callable

### ISSUE THREAD

**Issue by hfutdzx** [Pointcept/Pointcept#155]
thank you for your amazing work,but sorry,i need to trouble you again.

when i train ptv3 with ppt, i encounter this error message:
typeerror:’Point’ object is not callable.

(code:feat =self.proj_head(feat))

**Comment by Gofinge** [comment]
Hi, have you updated your code to v1.5.1? You can refer to the modification here (PPT model file).

<img width="1314" alt="image" src="https://github.com/Pointcept/Pointcept/assets/39218229/1c6e8826-4f17-4ee2-80f0-2fb465eb1b91">
