### ISSUE TITLE
About the implement of PTv1 vector attention.

### ISSUE THREAD

**Issue by jetpackfirstme** [Pointcept/Pointcept#157]
Thanks for your great work in 3D point cloud understanding! I've been reviewing the Point Transformer series, including PTv1, PTv2 and PTv3. After reading the paper and codes of PTv1, I found something confusing. In https://github.com/Pointcept/Pointcept/blob/247b621bdff6245ce36da3b1e683a118e67217be/pointcept/models/point_transformer/point_transformer_seg.py#L72-L76, I noticed that the calculation of vector attention is different from the paper, which is more like a grouped vector attention as you first divide the _x_v_ into _share_planes_ groups and only generate _out_planes_ / _share_planes_ weight coefficients for each value. I wonder whether my understanding is correct. Looking forward to your reply! Thank you!

**Comment by Gofinge** [comment]
Hi, your understanding is correct. We also add GVA to PTv1 to reduce the huge consumption of memory costs to make it more accessible. Yet there is still some difference between the kernel design of v1 and v2, resulting in a performance gap.
