### ISSUE TITLE
S3DIS preprocess

### ISSUE THREAD

**Issue by FT-Zheng** [Pointcept/Pointcept#16]
I have downloaded the Stanford3dDataset_v1.2.zip file and unzip it.
![image](https://user-images.githubusercontent.com/94618716/233930121-dc867de8-d616-4e9b-8cea-3c19ab1eba8b.png)
Then I tried to preprocess using the ‘python pointcept/datasets/preprocessing/s3dis/preprocess_s3dis.py --dataset_root ${S3DIS_DIR} --output_root ${PROCESSED_S3DIS_DIR} --align_angle’ and encountered the following problem.
![image](https://user-images.githubusercontent.com/94618716/233930573-d2fd208b-a10a-4793-9226-5db13d080cf8.png)

**Comment by FT-Zheng** [comment]
Thank you for your reply. This error occurred after I fixed the bug in https://github.com/Gofinge/PointTransformerV2/issues/8.

**Comment by FT-Zheng** [comment]
The incorrect number occurs in Line 323474 of the file S3DIS/Stanford3dDataset_v1.2/Area_5/office_19/Annotations/ceiling_1.txt
Correct the number 103.0�0000 to 103.000000.

**Comment by Gofinge** [comment]
Maybe we can add it to the Readme.

**Comment by FT-Zheng** [comment]
Thank you.
