### ISSUE TITLE
Confusion about `ElasticDistortion`

### ISSUE THREAD

**Issue by RayYoh** [Pointcept/Pointcept#168]
Hi, Xiaoyang.
I have one question about the data augmentation `ElasticDistortion`. 

Recently I find that after `ElasticDistortion`, the coords are changed and then used as feat keys in some configs. But in the code of PointGroup and some other code base (like SoftGroup), they usually identify xyz and xyz_middle to classify coords, and use xyz for voxelization and use xyz_middle as part of feats.

But in Pointcept, it seems merge these two as one.

**Comment by Gofinge** [comment]
Yes, in my opinion, the partial target of data augmentation is to simulate data that is not collected in the dataset. So coord used for both positional information and feature representation should be aligned. I didn't ablate the differences and just decided to unify them when I initially designed the framework of Pointcept.

**Comment by RayYoh** [comment]
Okay, got that. Thanks for your prompt reply.
