### ISSUE TITLE
CUDA error: the provided PTX was compiled with an unsupported toolchain.

### ISSUE THREAD

**Issue by aldinorizaldy** [Pointcept/Pointcept#169]
Many thanks for the amazing codebase. 

I'm on HPC cluster and using SLURM container for my environment with CUDA 11.7 and pytorch 1.13.

I'm running `sh scripts/train.sh -g 1 -d s3dis -c semseg-spunet-v1m1-0-base -n semseg-spunet-v1m1-0-base` but got this error. 

<img width="1085" alt="image" src="https://github.com/Pointcept/Pointcept/assets/52752546/760e8551-5407-4075-ab92-3606f9a7a88f">

**Comment by aldinorizaldy** [comment]
Thanks for quick answer. Really appreciate it. I was suspecting Pointops as well, but after compiling I can import pointops successfully `from pointops import knn_query_and_group`. I am using A100 and here is how I compile Pointops `TORCH_CUDA_ARCH_LIST="8.0" python  setup.py install`

This is the nvcc version:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
```

Any ideas how to solve the problem?

Thank you!

**Comment by Gofinge** [comment]
Hi, here is my suggestion:

Step 1, check whether PyTorch is well-installed:
```python
import torch
torch.cuda.is_available()
print(torch.version.cuda)
```

Step 2, rebuild pointops without a TORCH_CUDA_ARCH_LIST:
```bash
rm -rf build
python setup.py install
```

**Comment by aldinorizaldy** [comment]
Hi, I think the problem is I don't have CUDA inside the container. 

<img width="556" alt="image" src="https://github.com/Pointcept/Pointcept/assets/52752546/8762f360-7a8c-4aec-8a2e-0a12707d480c">

I compiled Pointops inside the container. I also got message: `No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda' `during compiling Pointops. After compiling Pointops inside the container, I installed packages with pip inside the container, 

What I don't understand is after I build the container, and run the container, I can import Pointops. But somehow my problem is with compiling Pointops.

<img width="450" alt="image" src="https://github.com/Pointcept/Pointcept/assets/52752546/0a5c6930-f992-4ee8-9a1e-994da5fd057a">


Also, this is what is inside /usr/local/

<img width="575" alt="image" src="https://github.com/Pointcept/Pointcept/assets/52752546/4063ac20-2653-48b4-9ac5-4e5702305415">


and /usr/local/cuda/

<img width="704" alt="image" src="https://github.com/Pointcept/Pointcept/assets/52752546/27975ba2-eb34-4ce4-b4ef-9f855fbf1d02">

I downloaded the container fro here:` https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch.` As the container already has pytorch, I didn't install pytorch anymore.

Do you think there is something wrong with the order of what I did:
1. Install packages inside container.
2. Compile Pointops inside container.
3. Build container
4. Run container

Many thanks!

**Comment by Gofinge** [comment]
Try this:
https://hub.docker.com/r/pointcept/pointcept/tags

**Comment by aldinorizaldy** [comment]
It works!! Thank you so much for providing docker container!! You are so amazing!! 
Please continue the fantastic job and sharing with the community, I really appreciate your works!!
