### ISSUE TITLE
CUDA out of memory during evaluation

### ISSUE THREAD

**Issue by Charlie839242** [Pointcept/Pointcept#170]
Hi, thanks for sharing your great work!
I modified the PTv3 model a little (adding some other components)  and was able to run it on three 3090 with a total batchsize of 6. The training was all normal. However, after the first or second epoch (I ran several times, the error occurs randomly after the first epoch or the second epoch), during evaluation, the error "cuda out of memory" was reported. I was wondering in what case will cause this kind of error? Because from my point of view the training wouldn't take mucher memory than evaluation. 
Looking forward to your replay : )

**Comment by Charlie839242** [comment]
Besides, the dataset and dataloader is the same  as provided. (S3DIS)

**Comment by Gofinge** [comment]
Hi, we run our code with a100. In your case, you can consider reducing the default grid size from 0.02 to 0.04.

**Comment by Charlie839242** [comment]
Hi, I found that it seems to be a issue with the "sync_bn". After enabling "empty_cache" the training will not be broken by CUDA out of memory. Thank you for your advice.
By the way, I am wondering whther you train the model in a single A100? Will  disabling "sync_bn" cause some performance drop if using multiple gpus?
Thanks for your reply!

**Comment by Gofinge** [comment]
Usually, I train models with 4 or 8 a100, so I am unsure about the case with a single GPU.

**Comment by Charlie839242** [comment]
I got it, thank you!
But I see the default setting is 'sync_bn=False'. Will setting sync_bn=True make a batchnorm in larger batchsize thus achieve a greater performance?

**Comment by Gofinge** [comment]
This point is too minor for a huge difference, I haven't ablated the difference after PTv2 finished. Maybe you can try to ablate the two settings.

**Comment by Charlie839242** [comment]
Thanks a lot for your reply!

**Comment by Miki-lin** [comment]
I meet the same problem, I find that the usage of the GPU memory kept increasing during the validation process, please check if there are any variables that were not cleaned up during the validation process

**Comment by Gofinge** [comment]
> I meet the same problem, I find that the usage of the GPU memory kept increasing during the validation process, please check if there are any variables that were not cleaned up during the validation process

Sorry for the late response. It is usually for point clouds, as the shape is not fixed, which finally results in some waste in memory.
