### ISSUE TITLE
Precise Evaluation

### ISSUE THREAD

**Issue by Charlie839242** [Pointcept/Pointcept#171]
Hi, thanks for sharing your great work!
I am wondering if there is a way to conduct precise evaluation after every epoch. Which part of config should I modified?
Looking forward to your reply :  )

**Comment by Gofinge** [comment]
It is too time-consuming to conduct our fragment-based precise evaluation. Yet we support an interpolate strategy which also can provide a precise performance during evaluation. Refer to configs for S3DIS. (https://github.com/Pointcept/Pointcept/blob/main/configs/s3dis/semseg-pt-v3m1-0-rpe.py#L141, https://github.com/Pointcept/Pointcept/blob/main/configs/s3dis/semseg-pt-v3m1-0-rpe.py#L154)
