### ISSUE TITLE
ValueError: Trainer: OneCycleLR: Expected positive integer total_steps, but got 0

### ISSUE THREAD

**Issue by Laventna** [Pointcept/Pointcept#173]
A reply would be greatly appreciated! The problems I have encountered are as follows:

Experiment name: semseg-pt-v3m1-0-rpe
Python interpreter dir: python
Dataset: s3dis
Config: semseg-pt-v3m1-0-rpe
GPU Num: 2

config:
weight = None
resume = False
evaluate = True
test_only = False
seed = 49124714
save_path = 'exp/s3dis/semseg-pt-v3m1-0-rpe'
num_worker = 10
batch_size = 6
batch_size_val = None
batch_size_test = None
epoch = 3000
eval_epoch = 100
sync_bn = False
enable_amp = True
empty_cache = False
find_unused_parameters = False
mix_prob = 0.8
param_dicts = [dict(keyword='block', lr=0.0006)]
hooks = [
    dict(type='CheckpointLoader'),
    dict(type='IterationTimer', warmup_iter=2),
    dict(type='InformationWriter'),
    dict(type='SemSegEvaluator'),
    dict(type='CheckpointSaver', save_freq=None),
    dict(type='PreciseEvaluator', test_last=False)
]
train = dict(type='DefaultTrainer')
test = dict(type='SemSegTester', verbose=True)
model = dict(
    type='DefaultSegmentorV2',
    num_classes=13,
    backbone_out_channels=64,
    backbone=dict(
        type='PT-v3m1',
        in_channels=6,
        order=['z', 'z-trans', 'hilbert', 'hilbert-trans'],
        stride=(2, 2, 2, 2),
        enc_depths=(2, 2, 2, 6, 2),
        enc_channels=(32, 64, 128, 256, 512),
        enc_num_head=(2, 4, 8, 16, 32),
        enc_patch_size=(128, 128, 128, 128, 128),
        dec_depths=(2, 2, 2, 2),
        dec_channels=(64, 64, 128, 256),
        dec_num_head=(4, 4, 8, 16),
        dec_patch_size=(128, 128, 128, 128),
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        attn_drop=0.0,
        proj_drop=0.0,
        drop_path=0.3,
        shuffle_orders=True,
        pre_norm=True,
        enable_rpe=True,
        enable_flash=False,
        upcast_attention=True,
        upcast_softmax=True,
        cls_mode=False,
        pdnorm_bn=False,
        pdnorm_ln=False,
        pdnorm_decouple=True,
        pdnorm_adaptive=False,
        pdnorm_affine=True,
        pdnorm_conditions=('ScanNet', 'S3DIS', 'Structured3D')),
    criteria=[
        dict(type='CrossEntropyLoss', loss_weight=1.0, ignore_index=-1),
        dict(
            type='LovaszLoss',
            mode='multiclass',
            loss_weight=1.0,
            ignore_index=-1)
    ])
optimizer = dict(type='AdamW', lr=0.006, weight_decay=0.05)
scheduler = dict(
    type='OneCycleLR',
    max_lr=[0.006, 0.0006],
    pct_start=0.05,
    anneal_strategy='cos',
    div_factor=10.0,
    final_div_factor=1000.0)
dataset_type = 'S3DISDataset'
data_root = 'data/s3dis'
data = dict(
    num_classes=13,
    ignore_index=-1,
    names=[
        'ceiling', 'floor', 'wall', 'beam', 'column', 'window', 'door',
        'table', 'chair', 'sofa', 'bookcase', 'board', 'clutter'
    ],
    train=dict(
        type='S3DISDataset',
        split=('Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_6'),
        data_root='data/s3dis',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(
                type='RandomDropout',
                dropout_ratio=0.2,
                dropout_application_ratio=0.2),
            dict(
                type='RandomRotate',
                angle=[-1, 1],
                axis='z',
                center=[0, 0, 0],
                p=0.5),
            dict(
                type='RandomRotate',
                angle=[-0.015625, 0.015625],
                axis='x',
                p=0.5),
            dict(
                type='RandomRotate',
                angle=[-0.015625, 0.015625],
                axis='y',
                p=0.5),
            dict(type='RandomScale', scale=[0.9, 1.1]),
            dict(type='RandomFlip', p=0.5),
            dict(type='RandomJitter', sigma=0.005, clip=0.02),
            dict(type='ChromaticAutoContrast', p=0.2, blend_factor=None),
            dict(type='ChromaticTranslation', p=0.95, ratio=0.05),
            dict(type='ChromaticJitter', p=0.95, std=0.05),
            dict(
                type='GridSample',
                grid_size=0.02,
                hash_type='fnv',
                mode='train',
                return_grid_coord=True),
            dict(type='SphereCrop', sample_rate=0.6, mode='random'),
            dict(type='SphereCrop', point_max=204800, mode='random'),
            dict(type='CenterShift', apply_z=False),
            dict(type='NormalizeColor'),
            dict(type='ToTensor'),
            dict(
                type='Collect',
                keys=('coord', 'grid_coord', 'segment'),
                feat_keys=('color', 'normal'))
        ],
        test_mode=False,
        loop=30),
    val=dict(
        type='S3DISDataset',
        split='Area_5',
        data_root='data/s3dis',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(
                type='Copy',
                keys_dict=dict(coord='origin_coord',
                               segment='origin_segment')),
            dict(
                type='GridSample',
                grid_size=0.02,
                hash_type='fnv',
                mode='train',
                return_grid_coord=True),
            dict(type='CenterShift', apply_z=False),
            dict(type='NormalizeColor'),
            dict(type='ToTensor'),
            dict(
                type='Collect',
                keys=('coord', 'grid_coord', 'origin_coord', 'segment',
                      'origin_segment'),
                offset_keys_dict=dict(
                    offset='coord', origin_offset='origin_coord'),
                feat_keys=('color', 'normal'))
        ],
        test_mode=False),
    test=dict(
        type='S3DISDataset',
        split='Area_5',
        data_root='data/s3dis',
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(type='NormalizeColor')
        ],
        test_mode=True,
        test_cfg=dict(
            voxelize=dict(
                type='GridSample',
                grid_size=0.02,
                hash_type='fnv',
                mode='test',
                keys=('coord', 'color', 'normal'),
                return_grid_coord=True),
            crop=None,
            post_transform=[
                dict(type='CenterShift', apply_z=False),
                dict(type='ToTensor'),
                dict(
                    type='Collect',
                    keys=('coord', 'grid_coord', 'index'),
                    feat_keys=('color', 'normal'))
            ],
            aug_transform=[[{
                'type': 'RandomScale',
                'scale': [0.9, 0.9]
            }], [{
                'type': 'RandomScale',
                'scale': [0.95, 0.95]
            }], [{
                'type': 'RandomScale',
                'scale': [1, 1]
            }], [{
                'type': 'RandomScale',
                'scale': [1.05, 1.05]
            }], [{
                'type': 'RandomScale',
                'scale': [1.1, 1.1]
            }],
                           [{
                               'type': 'RandomScale',
                               'scale': [0.9, 0.9]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [0.95, 0.95]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1, 1]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1.05, 1.05]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }],
                           [{
                               'type': 'RandomScale',
                               'scale': [1.1, 1.1]
                           }, {
                               'type': 'RandomFlip',
                               'p': 1
                           }]])))

num_worker_per_gpu = 5
batch_size_per_gpu = 3
batch_size_val_per_gpu = 1
batch_size_test_per_gpu = 1

Traceback (most recent call last):
  File "exp/s3dis/semseg-pt-v3m1-0-rpe/code/tools/train.py", line 41, in <module>
    main()
  File "exp/s3dis/semseg-pt-v3m1-0-rpe/code/tools/train.py", line 30, in main
    launch(
  File "/home/ytt24/PT/Pointcept-main/exp/s3dis/semseg-pt-v3m1-0-rpe/code/pointcept/engines/launch.py", line 74, in launch
    mp.spawn(
  File "/home/ytt24/anaconda3/envs/pointtrans/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 241, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/home/ytt24/anaconda3/envs/pointtrans/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/home/ytt24/anaconda3/envs/pointtrans/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 158, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/ytt24/PT/Pointcept-main/exp/s3dis/semseg-pt-v3m1-0-rpe/code/pointcept/utils/registry.py", line 53, in build_from_cfg
    return obj_cls(**args)
  File "/home/ytt24/PT/Pointcept-main/exp/s3dis/semseg-pt-v3m1-0-rpe/code/pointcept/utils/scheduler.py", line 128, in __init__
    super().__init__(
  File "/home/ytt24/anaconda3/envs/pointtrans/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 1649, in __init__
    raise ValueError(f"Expected positive integer total_steps, but got {total_steps}")
ValueError: Expected positive integer total_steps, but got 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ytt24/PT/Pointcept-main/exp/s3dis/semseg-pt-v3m1-0-rpe/code/pointcept/utils/registry.py", line 53, in build_from_cfg
    return obj_cls(**args)
  File "/home/ytt24/PT/Pointcept-main/exp/s3dis/semseg-pt-v3m1-0-rpe/code/pointcept/engines/train.py", line 142, in __init__
    self.scheduler = self.build_scheduler()
  File "/home/ytt24/PT/Pointcept-main/exp/s3dis/semseg-pt-v3m1-0-rpe/code/pointcept/engines/train.py", line 281, in build_scheduler
    return build_scheduler(self.cfg.scheduler, self.optimizer)
  File "/home/ytt24/PT/Pointcept-main/exp/s3dis/semseg-pt-v3m1-0-rpe/code/pointcept/utils/scheduler.py", line 147, in build_scheduler
    return SCHEDULERS.build(cfg=cfg)
  File "/home/ytt24/PT/Pointcept-main/exp/s3dis/semseg-pt-v3m1-0-rpe/code/pointcept/utils/registry.py", line 214, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/ytt24/PT/Pointcept-main/exp/s3dis/semseg-pt-v3m1-0-rpe/code/pointcept/utils/registry.py", line 56, in build_from_cfg
    raise type(e)(f"{obj_cls.__name__}: {e}")
ValueError: OneCycleLR: Expected positive integer total_steps, but got 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ytt24/anaconda3/envs/pointtrans/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 68, in _wrap
    fn(i, *args)
  File "/home/ytt24/PT/Pointcept-main/exp/s3dis/semseg-pt-v3m1-0-rpe/code/pointcept/engines/launch.py", line 137, in _distributed_worker
    main_func(*cfg)
  File "/home/ytt24/PT/Pointcept-main/exp/s3dis/semseg-pt-v3m1-0-rpe/code/tools/train.py", line 19, in main_worker
    trainer = TRAINERS.build(dict(type=cfg.train.type, cfg=cfg))
  File "/home/ytt24/PT/Pointcept-main/exp/s3dis/semseg-pt-v3m1-0-rpe/code/pointcept/utils/registry.py", line 214, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/ytt24/PT/Pointcept-main/exp/s3dis/semseg-pt-v3m1-0-rpe/code/pointcept/utils/registry.py", line 56, in build_from_cfg
    raise type(e)(f"{obj_cls.__name__}: {e}")
ValueError: Trainer: OneCycleLR: Expected positive integer total_steps, but got 0

**Comment by Gofinge** [comment]
Same as the issue here and some other issues (https://github.com/Pointcept/Pointcept/issues/88#issuecomment-2001883280). 
> ValueError: Trainer: OneCycleLR: Expected positive integer total_steps, but got 0
Typically because data paths do not contain valid data.

**Comment by Laventna** [comment]
thanks a lot

**Comment by Laventna** [comment]
Sorry to bother you again! The above problem has been solved, but I've run into some new problems. Details are as follows.

In the Train: [5/100][2027/3060], got the loss is NaN, " NaN or Inf found in input tensor"  and after that  a lot of trains are same as this

**RuntimeError:** CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Config:(Where I've made changes)**
num_worker = 4
batch_size = 2

 dict(        type='GridSample',
                grid_size=0.04,
                hash_type='fnv',
                mode='train',
                return_grid_coord=True),

**Complete train log:**
[train318_b2w4sp4.txt](https://github.com/Pointcept/Pointcept/files/14649292/train318_b2w4sp4.txt)

**Data** :  the processed data provided

**Device:**:
![image](https://github.com/Pointcept/Pointcept/assets/153786219/a82944df-7b9d-418a-86c2-eebb0b010e3b)

Can I run this project with 2 gpus(figure above)?  How to reset the config?

**Comment by Gofinge** [comment]
The batch size is too small, and the gradient is not stable, causing gradient explosion. Another solution that might effective is to disable AMP.
