### ISSUE TITLE
Question about preprocessing S3DIS dataset

### ISSUE THREAD

**Issue by Garhoode** [Pointcept/Pointcept#176]
I have downloaded S3DIS dataset `Stanford3dDataset_v1.2`. So I used the command `python pointcept/datasets/preprocessing/s3dis/preprocess_s3dis.py --dataset_root ${S3DIS_DIR} --output_root ${PROCESSED_S3DIS_DIR} --align_angle` to preprocess.
However, the code get stack as following showed
```
Loading room information ...
Processing scenes...
max_cpu_count:  20
Parsing: Area_1/conferenceRoom_1
Parsing: Area_1/conferenceRoom_2
Parsing: Area_1/copyRoom_1
Parsing: Area_1/hallway_1
Parsing: Area_1/hallway_2
Parsing: Area_1/hallway_3
Parsing: Area_1/hallway_4
Parsing: Area_1/hallway_5
Parsing: Area_1/hallway_6
Parsing: Area_1/hallway_7
Parsing: Area_1/hallway_8
Parsing: Area_1/office_1
Parsing: Area_1/office_2
Parsing: Area_1/office_3
Parsing: Area_1/office_4
Parsing: Area_1/office_5
Parsing: Area_1/office_6
Parsing: Area_1/office_7
Parsing: Area_1/office_8
Parsing: Area_1/office_9
```
And the cpu, ram are both low occupied.
I don't know what's the matter, could anyone do me a favor?

**Comment by Gofinge** [comment]
That's an irregular case. yet you can directly download my preprocessed S3DIS, detail is available in the dataset preprocessing README.

**Comment by Garhoode** [comment]
okay, thanks for your answer.
