### ISSUE TITLE
I have a question about the performance of PTv3 on nuScenes

### ISSUE THREAD

**Issue by WeijianZhang123** [Pointcept/Pointcept#180]
Hi, thanks for your great work!

I ran the PTv3 on nuScenes val set with the default config _semseg-pt-v3m1-0-base.py_, but only got 78.33 mIoU (lower than 80.4 reported in the paper). Could you please give me some advice?

Here's my environment:
4 RTX 4090 GPUs
PyTorch == 1.12
CUDA==11.3
flash-attn==2.5.6

Here's my result:
![image](https://github.com/Pointcept/Pointcept/assets/27566746/11777635-5112-4f8b-a0fd-b38350aba4aa)

**Comment by Gofinge** [comment]
Hi, running three times and choosing the highest might be a good choice. Model performances on point cloud datasets are always not so stable. An example log is available here (https://huggingface.co/Pointcept/PointTransformerV3/blob/main/nuscenes-semseg-pt-v3m1-0-base/train.log)

**Comment by WeijianZhang123** [comment]
Thanks for your quick reply! I have found the reason. 

I got the 78.33 mIoU from the **_val_** evaluation stage:
![image](https://github.com/Pointcept/Pointcept/assets/27566746/644fc628-35a5-4a22-981f-cfd31130fe8a)

And the performance is equal to your 78.31 mIoU:
![image](https://github.com/Pointcept/Pointcept/assets/27566746/98e96b6e-14b3-4788-91c2-82b21d4017e8)

Your reported 80.32 mIoU is from the **_test_** evaluation stage:
![image](https://github.com/Pointcept/Pointcept/assets/27566746/37fa93d3-1644-44f3-898e-d0e9ba40619b)
![image](https://github.com/Pointcept/Pointcept/assets/27566746/1cf04e40-f294-4cf5-97c1-69cc83796707)


Could you kindly explain the difference between these two types of evaluations? ( Maybe it's a stupid question :sweat:

**Comment by Gofinge** [comment]
Hi, Readme here (https://github.com/Pointcept/Pointcept?tab=readme-ov-file#testing) might be helpful.

**Comment by WeijianZhang123** [comment]
Thanks for your helpful reply!

**Comment by yxchng** [comment]
@WeijianZhang123 Do you manage to reproduce eventually?
