### ISSUE TITLE
Error at the installation. 

### ISSUE THREAD

**Issue by Vonct** [Pointcept/Pointcept#185]
Hi, I'm trying to reproduce your great work. I run the commands on installation guide. Everything goes well until the `python setup.py install`. The error comes below.

My environment:
1. CUDA11.8
2. Pytorch 2.0.0
3. ubuntu 20.04

After searching similar error, I still could not find the solution. Do you know how to solve this problem?
Thanks in advance!

> `No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
> running install
> /home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
> 
> 
>         ********************************************************************************
>         Please avoid running ``setup.py`` directly.
>         Instead, use pypa/build, pypa/installer or other
>         standards-based tools.
> 
>         See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
>         ********************************************************************************
> 
> 
>   self.initialize_options()
> /home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
> 
> 
>         ********************************************************************************
>         Please avoid running ``setup.py`` and ``easy_install``.
>         Instead, use pypa/build, pypa/installer or other
>         standards-based tools.
> 
>         See https://github.com/pypa/setuptools/issues/917 for details.
>         ********************************************************************************
> 
>   self.initialize_options()
> running bdist_egg
> running egg_info
> writing pointops2.egg-info/PKG-INFO
> writing dependency_links to pointops2.egg-info/dependency_links.txt
> writing requirements to pointops2.egg-info/requires.txt
> writing top-level names to pointops2.egg-info/top_level.txt
> reading manifest file 'pointops2.egg-info/SOURCES.txt'
> writing manifest file 'pointops2.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_py
> running build_ext
> Traceback (most recent call last):
>   File "setup.py", line 19, in <module>
>     setup(
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
>     return distutils.core.setup(**attrs)
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
>     return run_commands(dist)
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
>     dist.run_commands()
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
>     self.run_command(cmd)
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
>     super().run_command(command)
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
>     cmd_obj.run()
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/command/install.py", line 84, in run
>     self.do_egg_install()
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/command/install.py", line 132, in do_egg_install
>     self.run_command('bdist_egg')
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
>     self.distribution.run_command(command)
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
>     super().run_command(command)
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
>     cmd_obj.run()
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 167, in run
>     cmd = self.call_command('install_lib', warn_dir=0)
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
>     self.run_command(cmdname)
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
>     self.distribution.run_command(command)
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
>     super().run_command(command)
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
>     cmd_obj.run()
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
>     self.build()
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
>     self.run_command('build_ext')
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
>     self.distribution.run_command(command)
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
>     super().run_command(command)
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
>     cmd_obj.run()
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 88, in run
>     _build_ext.run(self)
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
>     self.build_extensions()
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 436, in build_extensions
>     self._check_cuda_version(compiler_name, compiler_version)
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 813, in _check_cuda_version
>     torch_cuda_version = packaging.version.parse(torch.version.cuda)
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 52, in parse
>     return Version(version)
>   File "/home/vonct/.conda/envs/pointcept/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 196, in __init__
>     match = self._regex.search(version)
> TypeError: expected string or bytes-like object`

**Comment by Gofinge** [comment]
Hi, it seems that you were trying to install pointops2. Note that pointops2 is only for Stratified Transformer and is not necessarily installed for Pointcept (pointops is needed). So may I confirm that you want to run Stratified Transformer? (I haven't tested ST for a long time.)

**Comment by Vonct** [comment]
> Hi, it seems that you were trying to install pointops2. Note that pointops2 is only for Stratified Transformer and is not necessarily installed for Pointcept (pointops is needed). So may I confirm that you want to run Stratified Transformer? (I haven't tested ST for a long time.)

Oh, I thought pointops2 just the updated version about pointops. I want to PTV3, but I also run the setup command in `pointops` folder. Same error.

**Comment by Gofinge** [comment]
Okay! As the error is raised from PyTorch. Typically, reinstalling the conda environment can solve most issues. I also have verified that PyTorch 2.x works well with our Pointcept.

**Comment by Vonct** [comment]
After I reinstall the environment for 2 times but with a **slightly different** command, I successfully finished the installation (Not run the code yet).
But I noticed that, if I use `pip` to install pytorch rather than `conda`. The above error would raise. Don't know how this cloud be.
Thank you for your reply. This issue could be closed. :)

**Comment by sultanfsn** [comment]
I am running into the same problem as you, can you please tell me more how you were able to solve it?

**Comment by Bryan1203** [comment]
I am also getting the same error, can you kindly explain how you solve it?
`(pointcept) bryanchang@threadripper:~/Pointcept/libs/pointops$ python setup.py install
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.3'
running install
/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing pointops.egg-info/PKG-INFO
writing dependency_links to pointops.egg-info/dependency_links.txt
writing requirements to pointops.egg-info/requires.txt
writing top-level names to pointops.egg-info/top_level.txt
reading manifest file 'pointops.egg-info/SOURCES.txt'
writing manifest file 'pointops.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying functions/grouping.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/utils.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/interpolation.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/attention.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/__init__.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/sampling.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/subtraction.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/aggregation.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/query.py -> build/lib.linux-x86_64-cpython-38/pointops
running build_ext
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    setup(
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup  
    return run_commands(dist)
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command       
    super().run_command(command)
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/command/install.py", line 87, in run     
    self.do_egg_install()
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/command/install.py", line 139, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command       
    super().run_command(command)
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 167, in run  
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command       
    super().run_command(command)
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run 
    self.build()
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 
110, in build
    self.run_command('build_ext')
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command       
    super().run_command(command)
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 91, in run   
    _build_ext.run(self)
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 424, in build_extensions
    self._check_cuda_version(compiler_name, compiler_version)
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 798, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 54, in parse
    return Version(version)
  File "/home/bryanchang/miniconda3/envs/pointcept/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 198, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object`

**Comment by Gofinge** [comment]
Check whether CUDA is correctly imported with the following script:  `nvcc -V`.

**Comment by Bryan1203** [comment]
The problem end up being nvidia nvml driver and library-version-mismatch and solve by following [this](https://stackoverflow.com/questions/43022843/nvidia-nvml-driver-library-version-mismatch).

**Comment by TheRealBeef** [comment]
I have an almost identical error, and it doesn't appear to be the mismatch as everything appears to match, and both `nvcc -V` and `nvidia-smi` run properly.

First I tried CUDA 12.4, which the GPU supports but pytorch doesn't quite support yet, then uninstalled everything/purged any configs/removed environment, reinstalled with CUDA 11.8, which just threw up compilation errors for setup.py, then uninstalled everything/purged any configs/removed environment, and now I'm back to the versions specified in the Readme.md with CUDA 11.3, and I have these errors.

**Comment by Gofinge** [comment]
Make sure the version of "nvcc -V" is aligned with CUDA version for your pre-build torch version. Then, rebuild the libs like Pointops with the environment.

**Comment by Miki-lin** [comment]
I set the cuda path as following and fix it!
```bash
export CUDA_HOME='/usr/local/cuda-11.3'
```

**Comment by Bryan1203** [comment]
just for reference:
I have been encountering this issue over and over, this fixed it:
pip uninstall torch
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu113

**Comment by Gofinge** [comment]
Just as rebooting your machine can fix most issues, carefully resetting your environment can also solve most.  ╮(╯▽╰)╭.
