### ISSUE TITLE
PTv3 for keypoint detection?

### ISSUE THREAD

**Issue by cpunion** [Pointcept/Pointcept#198]
I have a dataset consisting of rigged meshes, which includes vertices, fragments, and skeletons to which the meshes are skinned. How can I use PTv3 to predict the positions of the bones in the skeletons?

Additionally, there are specific requirements for the prediction task:
* The number of nodes (bones) and its order must be specified for output a tree structure. 
* These nodes typically do not lie directly on the mesh surface but are located at the joints.

Can PTv3 be adapted these requirements?

**Comment by Gofinge** [comment]
Hi, could you give me an explanation about "skeletons", and "the bones in the skeletons"? I only know the concept of vertex and edge in a mesh.

**Comment by cpunion** [comment]
@Gofinge Thanks for reply.

Perhaps joints are more suitable than bones. In the field of 3D animation, binding a 3D character's mesh to a skeleton is a crucial step for animating the character. This process allows us to drive the character's movements by manipulating the skeleton's displacement and rotation. Typically, this involves the following steps:

1. Creating the Skeleton: A skeleton structure is created for the mesh. This skeleton is usually made up of multiple joints, forming a hierarchical structure, with these joints usually located inside the mesh. Below some examples of mesh and skeleton (from https://www.researchgate.net/figure/Human-Skeleton-Model-with-15-Joints_fig3_349308622 , https://www.researchgate.net/figure/A-tetrahedral-mesh-and-the-underlying-skeleton_fig1_316857966)
![image](https://github.com/Pointcept/Pointcept/assets/8459/42d336a0-0228-4061-830d-c7ff7251cc29)
![image](https://github.com/Pointcept/Pointcept/assets/8459/ca9b1d56-ef84-4d9b-9d7e-61fa41aa4ac0)


2. Skinning: The vertices of the mesh are bound to these bones or joints. Therefore, any movement or rotation of the skeleton will drive the movement of the bound mesh vertices, thereby facilitating the animation of the character. See an examle (from https://medium.com/@junyingw/comparison-between-linear-blend-skinning-and-dual-quaternion-skinning-369e727fdcf6):
![image](https://github.com/Pointcept/Pointcept/assets/8459/7e404d34-09ca-4bd1-b4a0-3a6c9ed3fb89)


The initial step is to extract the coordinates of the skeletal joints base on a given number of joints. And then creating a hierarchical structure of the skeleton from those joints becomes relatively easy.

Joints should ideally be predicted from the vertices or faces surrounding them, as they are located within the mesh and have a certain relative relationship to each other.

Could this task potentially be addressed by making predictions from the outputs of an encoder or decoder of PTv3, combined with an MLP for regression? Alternatively, would employing cross-attention for a seq2seq model be a viable approach? Are there any other effective methods you might recommend?

**Comment by Gofinge** [comment]
Hi, thank you for your detailed explanation and now I have a clear overview of the question. PTv3 is a good backbone to extract strong points' representation (feature) to help you achieve the final goal, and so are other good 3D backbones. The major issue is how to design a framework that utilizes these points' representation to predict the information you want. Simple MLP won't work.

 So, I think an anchor-free object detection framework in 2D vision might have some inspiration. For example, you can predict a bias of each point and make a point + bias close to its key point. Then during inference, you can group point after shift with the bias, then maybe use the centre of points + offset as the key point. (A trivial and rough concept and suggestion)

**Comment by cpunion** [comment]
Thank you for your suggestion, I haven't fully understood it yet, I plan to conduct some preliminary experiments. I'm relatively unfamiliar with this area and would appreciate more details:

1. When using PTv3 as the backbone for feature extraction, is it more effective to use just the embedding or the output of the encoder/decoder? I'm not yet clear on the meaning of the output from the encoder/decoder.
2. For predicting the bias of points through extracted features, do you have any recommended models? I've briefly researched ViTPose for 2D image pose estimazation, which extracts features from a heatmap, but this method seems unsuitable for discrete point clouds. Additionally, would incorporating the prediction of keypoint index ([keypoint_idx, bias]) improve the prediction outcome?
3. Considering that a mesh wraps around joints and some vertices might not be bound to the nearest joint, does this imply that this approach might be inappropriate? Of course, this might be less of an issue with standard T-poses.

**Comment by Gofinge** [comment]
> 1. When using PTv3 as the backbone for feature extraction, is it more effective to use just the embedding or the output of the encoder/decoder? I'm not yet clear on the meaning of the output from the encoder/decoder.

Yes, using PTv3 for feature extraction is relatively stronger and faster than the existing backbones. The output from the encoder is the feature of points after multiple pooling; refer to u-net for image processing. The output of the decoder is feature representations of input points (refer to image backbone extract pixel features).

> 2. For predicting the bias of points through extracted features, do you have any recommended models? I've briefly researched ViTPose for 2D image pose estimazation, which extracts features from a heatmap, but this method seems unsuitable for discrete point clouds. Additionally, would incorporating the prediction of keypoint index ([keypoint_idx, bias]) improve the prediction outcome?

I am  not familiar with these works, but I think you can survey some papers related to "anchor-free object detection for image" and "key points detection for image". You can choose one as a baseline and adapt it to 3D point clouds. You can consider reading some code in our codebase, and then you will be familiar with how to handle these points as image pixels.

> Considering that a mesh wraps around joints and some vertices might not be bound to the nearest joint, does this imply that this approach might be inappropriate? Of course, this might be less of an issue with standard T-poses.

This is a unique characteristic of your problem, and you can consider solving it in your final design, such as adding a mechanism to judge the issue.

**Comment by cpunion** [comment]
@Gofinge Thank you very much for your detailed explanation. My understanding is much clearer now.

**Comment by iballester** [comment]
>  The major issue is how to design a framework that utilizes these points' representation to predict the information you want. Simple MLP won't work.

@Gofinge may I ask for more information about why a simple MLP won't work? Thank you!

**Comment by Gofinge** [comment]
Intuition, haha. The problem feels like something similar to detection.
