### ISSUE TITLE
Why not Voxilize the lidar point cloud for Point Transformer V3?

### ISSUE THREAD

**Issue by Osama26-byte** [Pointcept/Pointcept#201]
Hi, great work. I was curious why dont you voxilize the points of point cloud and then train the model?

**Comment by Gofinge** [comment]
Hi, GridSampling (https://github.com/Pointcept/Pointcept/blob/main/configs/nuscenes/semseg-pt-v3m1-0-base.py#L109) is exactly Voxelization. I think grid sampling is more proper as it is needed by most kinds of point cloud backbone.

**Comment by Osama26-byte** [comment]
Okay, thanks. 

Another question is why you are using offset operator? And what is required to train ptv3 with a normal batch size as you used offset2batch function for spvcnn and spunet etc?

**Comment by Gofinge** [comment]
An explanation of offset is available here (https://github.com/Pointcept/Pointcept?tab=readme-ov-file#offset). It is a similar concept to batch used in SpConv.

**Comment by yxchng** [comment]
`Hi, GridSampling (https://github.com/Pointcept/Pointcept/blob/main/configs/nuscenes/semseg-pt-v3m1-0-base.py#L109) is exactly Voxelization. I think grid sampling is more proper as it is needed by most kinds of point cloud backbone.`

what does more proper here mean? are they different?

**Comment by Gofinge** [comment]
Apology for the confusing description. Compared with "Voxelization", I think "GridSampling" is a more proper name for this process as it is beneficial to all real-world 3D perception tasks. It is a similar concept to "Resize" in image processing which defines the "resolution" of 3D point cloud.

**Comment by Osama26-byte** [comment]
Thanks.

Another question, does it matter to use ["z", "z-trans", "hilbert", "hilbert-trans"]? Can we just use the first 2 like ['z', 'z-trans']? what will be the effect of this?

**Comment by Gofinge** [comment]
> Thanks.
> 
> Another question, does it matter to use ["z", "z-trans", "hilbert", "hilbert-trans"]? Can we just use the first 2 like ['z', 'z-trans']? what will be the effect of this?

Hi this ablation is available in our paper Table 2.

**Comment by Osama26-byte** [comment]
Thanks alot.
