### ISSUE TITLE
Questions about SerializedPooling in PTv3

### ISSUE THREAD

**Issue by yijicheng** [Pointcept/Pointcept#204]
https://github.com/Pointcept/Pointcept/blob/6985fa399da72f26f6b6c406eb4b8951281fff81/pointcept/models/point_transformer_v3/point_transformer_v3m1_base.py#L341

Can the number of reduced points remain the same for different point clouds in one batch after `SerializedPooling` operation?

for example: batch_size=2
(input_point["batch"]==0).sum() == (input_point["batch"]==1).sum()
how to promise (output_point["batch"]==0).sum() == (output_point["batch"]==1).sum()?

**Comment by Gofinge** [comment]
Hi, I will delete the dummy issue~ 
Hope you can see the message from email.
