### ISSUE TITLE
About performance of the checkpoint on Huggingface

### ISSUE THREAD

**Issue by trinhtuanvubk** [Pointcept/Pointcept#209]
I have tested the model_best.pth on S3dis dataset but the acc is around 0.5 and mIoU is around 0.2.
I think its quite bad, Did you upload the best checkpoint or just upload an example for testing ?
Thank you

**Comment by Gofinge** [comment]
Hi, as mentioned in README, our model structured is adjusted, and the old model weight is not valid for the current version of the code. If you need to use this old released weight, you can use the code with tag 1.5.1 (https://github.com/Pointcept/Pointcept/releases/tag/v1.5.1).

**Comment by trinhtuanvubk** [comment]
Oh, thank you for the information. Do you have any plans for releasing checkpoint of the newest code ?

**Comment by Gofinge** [comment]
> formation. I have also test on 1.5.1 code version, the re

Remove your cached prediction (result) in exp_folder and run inference again.

**Comment by trinhtuanvubk** [comment]
It works perfectly, thank you for your guidance. Im looking forward to your new updates
