### ISSUE TITLE
About SpUNet implementation details.

### ISSUE THREAD

**Issue by jetpackfirstme** [Pointcept/Pointcept#21]
Hello, thanks for sharing the codes! I have a question about the implementation details of SpUNet. In the following code, the sparse_shape is added by 96. Could you please explain this code? Looking forward to your reply, thanks!
https://github.com/Pointcept/Pointcept/blob/864b9c4729c39a95c0a4e5a9f4087f5feafa5df4/pointcept/models/sparse_unet/spconv_unet_v1m1_base.py#L169

**Comment by Gofinge** [comment]
Aha, good question. When I try to run semantic kitti with SpUNet, since the Z-axis is not long enough, it leads to a bug during pooling (stride conv). Consequently, I pad some length in each axis to prevent it.
