### ISSUE TITLE
Inquiry about the default config of PTv3

### ISSUE THREAD

**Issue by RayYoh** [Pointcept/Pointcept#214]
Hi Xiaoyang. I find that the default config [here](https://github.com/Pointcept/Pointcept/blob/c759914eb3ab8255455c80c00472ab0bc664a20c/configs/scannet/semseg-pt-v3m1-0-base.py#L20C8-L25C41) of PTv3 in this repo is a little bit different from the original paper (stages and dec depth).
![image](https://github.com/Pointcept/Pointcept/assets/35106336/8c9292f7-93ae-4b59-bc44-1315ae8c33c8)
Does the current config get better performance than the paper? Thx.

**Comment by Gofinge** [comment]
Oh, yes. But trust me, the parameter doesn't matter so much. The scale of a model should go with the scale of data.

**Comment by RayYoh** [comment]
Got that. Agree with you. I find that the result on ScanNet v2 Val set is just 0.1% larger than the paper. lol
