### ISSUE TITLE
When will the valid weights for PTv3 be released?

### ISSUE THREAD

**Issue by JiajieLi7012** [Pointcept/Pointcept#215]
Hello, as mentioned in the README file, the current released weights for PTv3 are invalid because the architecture of the PTv3 was adjusted. I'm wondering when usable weights of PTv3 will be released or which commit  I should roll back to if I want to use currently released weights. Or pre-trained weights for PTv2 are also useful for me if you can provide them. Thanks in advance.

**Comment by Gofinge** [comment]
Hi, roll back to the v1.5.1 tag (https://github.com/Pointcept/Pointcept/releases/tag/v1.5.1).

**Comment by QWTforGithub** [comment]
> Hello, as mentioned in the README file, the current released weights for PTv3 are invalid because the architecture of the PTv3 was adjusted. I'm wondering when usable weights of PTv3 will be released or which commit I should roll back to if I want to use currently released weights. Or pre-trained weights for PTv2 are also useful for me if you can provide them. Thanks in advance.

Hi, it seems that the training weights of PTv3 cannot be downloaded at present. Would you like to share the training weights you downloaded before (preferably ScanNet)?

**Comment by Gofinge** [comment]
Hi, model weights can be downloaded on the hugging face page and run with the code tag with v1.5.1. Re-train model weights for the new structure will cost lots of computing resources, and I am working on a new research project. I will retrain for the current version when I have some free resources.

**Comment by QWTforGithub** [comment]
> Hi, model weights can be downloaded on the hugging face page and run with the code tag with v1.5.1. Re-train model weights for the new structure will cost lots of computing resources, and I am working on a new research project. I will retrain for the current version when I have some free resources.

Thank you very much. I can get it.

**Comment by tanmay4269** [comment]
on this git commit [Pointcept/Pointcept at v1.5.1](https://github.com/Pointcept/Pointcept/tree/v1.5.1), i tested on [these model weights](https://huggingface.co/Pointcept/PointTransformerV3/tree/main/scannet-semseg-pt-v3m1-0-base) but there were conflict in model weights.
im not sure where to find the right weights or where im going wrong.

**Comment by Gofinge** [comment]
What kind of conflict did you encounter?

**Comment by tanmay4269** [comment]
Here't the entire output: https://pastebin.com/vYZN1wrR

**Comment by tanmay4269** [comment]
@Gofinge is there an issue from my side?

**Comment by Gofinge** [comment]
> @Gofinge is there an issue from my side?

Could you provide the details log not just the error message? I can check the config and setting.

**Comment by tanmay4269** [comment]
fixed, was using wrong config file
