### ISSUE TITLE
Grid Size and Voxel Size

### ISSUE THREAD

**Issue by Osama26-byte** [Pointcept/Pointcept#224]
Hi, thanks for this great work. I was working on some pre processing techniques plus my cuda gets OOM when I use grid size of 0.05 for Waymo dataset. But in another work I used voxel generator with Voxel size of [0.1, 0.1, 0.15]. I want to know if Voxel size in another implementation and Grid Sampling in you implementation, voxel size and grid size are same thing? and can I use 0.1 for grid sampling?

**Comment by Gofinge** [comment]
Hi, it is the same thing, and you can set it to 0.1. The Waymo dataset contains more points compared with another outdoor dataset.

**Comment by Osama26-byte** [comment]
Thanks.
