### ISSUE TITLE
Question about fnv_hash

### ISSUE THREAD

**Issue by pycoco** [Pointcept/Pointcept#251]
Is it possible to implement the fnv_hash_vec method in pytorch? (it's not supported uint64/ uint32 in pytorch)

**Comment by Gofinge** [comment]
You can use our serialization strategy (PTv3, z-order) to achieve this.

**Comment by pycoco** [comment]
> You can use our serialization strategy (PTv3, z-order) to achieve this.

Thanks for your reply.   I'm a little confused.  Because grid_coord is the input of serialization strategy (PTv3, z-order) while fnv_hash_vec is used for generating grid_coord. How could i use serialization strategy to achieve this?

**Comment by pycoco** [comment]
> > You can use our serialization strategy (PTv3, z-order) to achieve this.
> 
> Thanks for your reply. I'm a little confused. Because grid_coord is the input of serialization strategy (PTv3, z-order) while fnv_hash_vec is used for generating grid_coord. How could i use serialization strategy to achieve this?

Got it, thanks!
