### ISSUE TITLE
s3dis preprocess error：Area_1_alignmentAngle.txt not found.

### ISSUE THREAD

**Issue by Yatoronto** [Pointcept/Pointcept#269]
run this then error:# S3DIS without aligned angle
python pointcept/datasets/preprocessing/s3dis/preprocess_s3dis.py --dataset_root ${S3DIS_DIR} --output_root ${PROCESSED_S3DIS_DIR}

**Comment by lbj-lonng** [comment]
Have you solved this problem?

**Comment by Gofinge** [comment]
It depends on which version of the Raw S3DIS dataset you download. Now an easier way to handle this is to download our processed version on Huggingface.

**Comment by lbj-lonng** [comment]
"Okay, thank you."
