### ISSUE TITLE
Can Point transformer v2 train on one 3090ti?

### ISSUE THREAD

**Issue by Pixie412** [Pointcept/Pointcept#27]
Hi,

Can point transformer v2 train on one 3090 ti?

**Comment by Gofinge** [comment]
Hi, I don't recommend that because batch size has a significant inference on the performance, and reducing the batch size to fit a single GPU will lead to a performance drop

**Comment by Gofinge** [comment]
Here are some links might be helpful:
https://github.com/Pointcept/Pointcept/blob/main/pointcept/engines/hooks/evaluator.py (hook which evaluate on voxelized point cloud)
https://github.com/Pointcept/Pointcept/blob/main/pointcept/engines/hooks/misc.py#L198 (hook which enable our testing process after training)

**Comment by Pixie412** [comment]
I encountered another problem:
![image](https://github.com/Pointcept/Pointcept/assets/72333326/de690477-fe79-4a3c-b490-66ac6113bee6)

Basically, I process each point cloud file with transform (e.g., CenterShift, Voxelize, Collect...) and save it into a local file. During evaluation, I load the local file with dataloader as
![image](https://github.com/Pointcept/Pointcept/assets/72333326/a3db0f37-ea77-4404-8aaa-ec234494a789)
It will output this error when send it into pointtransformer.
How can I solve this?
