### ISSUE TITLE
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### ISSUE THREAD

**Issue by hpc100** [Pointcept/Pointcept#275]
Hello,

Thank's for your amazing work.

I install Point Transformer V3 on A6000 GPU and when I run `CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=1 sh scripts/train.sh -g 1 -d s3dis -c semseg-pt-v3m1-1-rpe -n semseg-pt-v3m1-1-rpe` I got this error
 `RuntimeError: Trainer: CUDA error: the provided PTX was compiled with an unsupported toolchain.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`

I install point_opts and pointgroup_ops with TORCH_CUDA_ARCH_LIST="7.0 7.5 8.0 8.6+PTX"

Any solutions ?

Thank's in advance.

**Comment by Gofinge** [comment]
Hi, no need to set TORCH_CUDA_ARCH_LIST if you build the lib and run the lib on the same GPU arch.

**Comment by hpc100** [comment]
I got the same., with installing without TORCH_CUDA_ARCH_LIST and simply run python setup.py install

**Comment by Gofinge** [comment]
Yes, I used it to make docker environments.
