### ISSUE TITLE
Custom dataset patch_size cannot be converted to an integer multiple

### ISSUE THREAD

**Issue by jing-zhao9** [Pointcept/Pointcept#291]
When I run the ptv3 model with a custom dataset, I cannot divide the dataset into integer multiples of patch_size. May I ask if you have any suggestions?
![image](https://github.com/Pointcept/Pointcept/assets/104781102/98b63e7d-f8ac-48de-ab26-6e0b9b1d8829)

**Comment by Gofinge** [comment]
It should not be the reason. We have the necessary padding operation.

**Comment by jing-zhao9** [comment]
Thank you for your reply. It was my mistake. I didn't use flashAttention but it wasn't set to false
