### ISSUE TITLE
Pointcept Development - until June 2023

### ISSUE THREAD

**Issue by Gofinge** [Pointcept/Pointcept#3]
If you have any suggestions for Pointcept, please do not hesitate to leave a comment. Additionally, we would appreciate any contributions to Pointcept, particularly in the tasks listed below (with performance validation required). We also welcome releasing new work in Pointcept to help promote our community.

Task List:
- [x] Code release of `MSC`
- [ ] Code release of `CeCo`
- [x] Code release of `CAC`
- [x] Add support to the following pre-training framework:  `PointContrast`, `Contrastive Scene Contexts`
- [x] Add support to the following backbone: `OctFormer`
- [x] Add support to the following backbone: `Swin3D`
- [ ] Add support to the following backbone: `PointNeXt`
- [ ] Add support to the following semantic segmentation framework: [`SphereTransformer`](https://github.com/dvlab-research/SparseTransformer) (Semantic Kitti new sota)
- [x] Add support to the following instance segmentation framework: PointGroup
- [ ]  Add support to the following object detection framework: VoteNet
- [x] Add PreciseEvaluator, which enables our Tester after training
- [x] Add DDP Testing (Multi-GPU)
- [x] Better checkpoint saver and loader to support w and w/o DDP training

**Comment by RayYoh** [comment]
Hi Xiaoyang @Gofinge, may I ask if there is any version that includes VoteNet?

**Comment by Gofinge** [comment]
Oh @RayYoh , good question. Honestly, I don't have enough time to add support to more datasets. Even I know Pointcept really needs this to attract more users.

**Comment by RayYoh** [comment]
Yeah, thanks for your great efforts. I am wondering whether some object detection methods (such as VoteNet) are integrated into Pointcept. I see in #262 that someone also requested these.

**Comment by Gofinge** [comment]
That one was build upon OpenPCDet. I also always hope I can make Pointcept equip with Object Detection, but unfortunately, I have to give up the plan due to time schedule.

**Comment by RayYoh** [comment]
I see, thank you.
