### ISSUE TITLE
Difference between queryandgroup and knn_query + grouping

### ISSUE THREAD

**Issue by ayushjain1144** [Pointcept/Pointcept#30]
Hi, 

Thank you so much for your very nice work!

In your PTv1, I think you used to use `queryandgroup` while in PTv2 you are using knn_query + grouping. Is there any difference between the two? In my project, I was following PTv1 earlier and was wondering if its safe to shift to the new knn_query+grouping and if it would be exactly equivalent. In my early checks, `torch.allclose` between the two methods is False

Thank you so much!

**Comment by Gofinge** [comment]
Hi, there is no difference. I just separate the two operators.

**Comment by ayushjain1144** [comment]
Thank you for the quick reply!!
