### ISSUE TITLE
Testing Results are very low

### ISSUE THREAD

**Issue by SpeedyGonzales949** [Pointcept/Pointcept#307]
Hi, I manage to train PTv3 on a custom dataset, and got pretty good results for validation, over 80% iou for most classes. However, when I test using the test script, the least sampled class drops iou to 9%, while the accuracy is over 80% I do want to mention that all other classes achieve decent, normal results. with all metrics around 80%. Is it because of the interpolation or the chosen grid_size is too big ? I decided to go with this grid_size because I have a very high dense point cloud, about 37 points / m^2 and each pc has around 90k points.

I am thinking that the model predicts to many false positives for that specific class, and when it gets to interpolation, those values are mutlplying themselves. Any other ideas , why this might happen ? Any help is highly appreciated.
This is my config for the test set. 
```python
        transform=[
            dict(type='CenterShift', apply_z=True),
            dict(type='Copy', keys_dict=dict(segment='origin_segment')),
            dict(
                type='GridSample',
                grid_size=0.25,
                hash_type='fnv',
                mode='train',
                keys=('coord', 'strength', 'segment'),
                return_inverse=True),
            dict(type='CenterShift', apply_z=False),
        ],
        test_mode=True,
        test_cfg=dict(
            voxelize=dict(
                type='GridSample',
                grid_size=0.25,
                hash_type='fnv',
                mode='test',
                return_grid_coord=True,
                keys=('coord', 'strength')),
            crop=None,
            post_transform=[
                dict(type='ToTensor'),
                dict(
                    type='Collect',
                    keys=('coord', 'grid_coord', 'index'),
                    feat_keys=('coord', 'strength'))
            ],
            aug_transform=[[{
                'type': 'RandomRotateTargetAngle',
                'angle': [0],
                'axis': 'z',
                'center': [0, 0, 0],
                'p': 1
            }]]),
```

From past issue like this #164 , I do understand that validation results are not that accuracte. However I dont think it justifies this sudden drop.

Update: I found issue https://github.com/Pointcept/PointTransformerV3/issues/9 . I will check now the inconsistencies in the trasnformation pipeline between training vlaidation and testing.

**Comment by SpeedyGonzales949** [comment]
Update: I solved the issue. Got a 85% mIoU, and all classes have normal-looking metrics I removed the GridSample from transform in the test dict and made sure that test pipeline matches with train pipeline. This is my final config.
```python
transform=[
            dict(type='CenterShift', apply_z=True)
        ],
        test_mode=True,
        test_cfg=dict(
            voxelize=dict(
                type='GridSample',
                grid_size=0.25,
                hash_type='fnv',
                mode='test',
                return_grid_coord=True,
                keys=('coord', 'strength')),
            crop=None,
            post_transform=[
                dict(type='ToTensor'),
                dict(
                    type='Collect',
                    keys=('coord', 'grid_coord', 'index'),
                    feat_keys=('coord', 'strength'))
            ],
            aug_transform=[[{
                'type': 'RandomRotateTargetAngle',
                'angle': [0],
                'axis': 'z',
                'center': [0, 0, 0],
                'p': 1
            }]]),
```

**Comment by Gofinge** [comment]
It's good to see the issue is already solved. Sorry for the late response.
