### ISSUE TITLE
Request on Preparing Training Dataset for PTV3

### ISSUE THREAD

**Issue by JulesWang1999** [Pointcept/Pointcept#325]
Hi. Thank you for your fantastic job.

I'm currently preparing to test PTV3 on my own dataset following the demo on S3DIS. I have already converted my data to match the structure of the preprocessed S3DIS data used in your demo(independent files of  coords, color, norms, and segments). 

However, I find the code structure a bit too complex to navigate. **Could you please let me know which file contains the code related to preparing the training dataset? I'm particularly interested in the sections concerning data loading and down-sampling.**

Thank you for your time.

**Comment by JulesWang1999** [comment]
Hi, I've noticed that the down-sampling function in your code (located at transform.py, line 187) seems to be solely controlled by the "RandomDropout" parameter, which can be set to 0. Does this mean that the length of the model input isn't fixed? As long as I have enough VRAM, can the model be fed with millions of points from a single data piece all at once? Thanks.

**Comment by Gofinge** [comment]
> 187 行）

Yes, we support dynamic shape, but millions of points is too much haha.

**Comment by JulesWang1999** [comment]
Thanks for your time.
