### ISSUE TITLE
Instance Segmantation about GridSample

### ISSUE THREAD

**Issue by wdczz** [Pointcept/Pointcept#330]
Hi all,

I saw that grid sample was used during the data processing phase. Will this result in a decrease in points? During the validation , grid sample was also used. Will this result in a smaller number of point clouds being validated (GT Instance is a normal quantity)

Thanks in advance

**Comment by Gofinge** [comment]
Actually, grid sampling unifies the “resolution” of point cloud. It makes a better feature extraction. We don’t need a too dense point cloud.

**Comment by wdczz** [comment]
Thank you for your answer. I have one more question, don't we need all the point clouds for testing or validation? Alternatively, during verification, we only need to validate the voxel point cloud. Then, based on the validation metrics to select the best model, perform inference on all point clouds during testing. I just got started and may not have a good understanding of this. Thank you for your reply.

**Comment by wdczz** [comment]
Apologies, upon re-reading the test code, I understand it as follows: during the test, voxels are filled to ensure resolution, and the data is divided into (maximum number of voxel count) segments for inference. Subsequently, these segments are merged to produce a comprehensive point cloud.

**Comment by Gofinge** [comment]
>  Then, based on the validation metrics to select the best model, perform inference on all point clouds during testing.

Yes, correct.

**Comment by Gofinge** [comment]
> Subsequently, these segments are merged to produce a comprehensive point cloud.
Yes.

**Comment by wdczz** [comment]
Thank you for your reply.
