### ISSUE TITLE
Question about test

### ISSUE THREAD

**Issue by PengxinWang** [Pointcept/Pointcept#334]
Hi, 

I'm learning point transformer v3 on semseg task for S3DIS dataset and want to ask questions about details in testing.
 
In [transform.py 855-858](https://github.com/Pointcept/Pointcept/blob/c4363c86e1e77325645d44bc8052b338031f1b30/pointcept/datasets/transform.py#L855), a list of data_part is sampled to traverse all points. 
```
for i in range(count.max()):
    idx_select = np.cumsum(np.insert(count, 0, 0)[0:-1]) + i % count
    idx_part = idx_sort[idx_select]
    data_part = dict(index=idx_part)
```
One problem is that distribution of points over different grids is quite uneven, only several grids are cramed with points, while most of grids only have a few points. Then those points are repeated during test, and preds of same point will be added together according to [test.py 195](https://github.com/Pointcept/Pointcept/blob/c4363c86e1e77325645d44bc8052b338031f1b30/pointcept/engines/test.py#L195), 
```
for be in input_dict["offset"]:
    pred[idx_part[bs:be], :] += pred_part[bs:be]
    bs = be
```
So my question is
1. will the preds of same points be the same during different test forward pass?
2. is it appropraite to average preds of same point?
3. data_list is quite long and will cause OOM problem during test, while it's fine during validation. So is repetition on points just useless or it will be helpful? And is there any suggestion to make remedy for the problem with limited resource?

I hope my code understanding is not wrong. Tks for ur help : )

**Comment by Gofinge** [comment]
> will the preds of same points be the same during different test forward pass?

We hope the network can learn the small difference in position and have a more precise prediction.

> is it appropriate to average preds of the same point?

I think current test process is average (sum) the pred of the same point

> data_list is quite long and will cause OOM problem during test, while it's fine during validation. So is repetition on points just useless or it will be helpful? And is there any suggestion to make remedy for the problem with limited resource?

Yes, refer to the test config [here](https://github.com/Pointcept/Pointcept/blob/main/configs/nuscenes/semseg-pt-v3m1-0-base.py#L160) for the outdoor dataset, we have a dual grid sampling to make it shorter. We only conduct voting from the second grid size to the first grid size and finally interpolate the result to the original resolution.
