### ISSUE TITLE
PTv3 Performance on nuScenes Test Split

### ISSUE THREAD

**Issue by c7huang** [Pointcept/Pointcept#336]
Thanks for releasing the code and weights for PTv3!

I am trying to reproduce some results on the nuScenes dataset as part of the verification process for my current project. However, I am encountering some performance discrepancies between the validation and test split.

On the **validation** split, I am able to reproduce the same (or better) performance than that reported in the paper, using the provided weights and our weights trained from scratch using the same config `semseg-pt-v3m1-0-base`. Evaluation is done using `python -m nuscenes.eval.lidarseg.evaluate` instead of the provided `test.sh`.
|                |  mIoU |
|---------------:|:----:|
| Paper (Tab. 7) | 80.4  |
|  Provided ckpt | 80.3  |
|  Ours (v1.5.1) | 81.1  |
|  Ours (latest) | 81.0  |

On the **test** split, however, I am not able to get the `82.7` mAP as reported in the paper. Worryingly, the model trained by us seems to have degraded performance (-1%), which is abnormal compared to other approaches where the test set mAP is typically higher than validation.
|                |  mIoU |
|---------------:|:----:|
| Paper (Tab. 7) | 82. 7 |
|  Provided ckpt | 81.2  |
|  Ours (v1.5.1) | 80.8  |
|  Ours (latest) | 80.3  |

The nuScenes dataset is freshly downloaded and the provided info pickle files are used. The inference is done exactly the same as the validation split, except the `split` is changed to `test` in the config. I am using the `python -m nuscenes.eval.lidarseg.validate_submission` command to validate and generate the submission zip file.

I am not too familiar with the nuScenes semantic segmentation challenge submission process. I am wondering if there is anything that I might have missed in the inference or submission process that could result in this degradation in performance. I would appreciate any help and clarifications. Thank you!

**Comment by Gofinge** [comment]
Hi, for the test split submission. We also use a multi-model ensemble which is also adopted by other works. Specifically, you can train three PTv3 separately and add their predicted logic to vote for the final prediction.

**Comment by c7huang** [comment]
Thank you! I was considering if ensemble and TTA were factors, glad to know that they are standard practices for test set submissions.

**Comment by CacatuaAlan** [comment]
> Thanks for releasing the code and weights for PTv3!
> 
> I am trying to reproduce some results on the nuScenes dataset as part of the verification process for my current project. However, I am encountering some performance discrepancies between the validation and test split.
> 
> On the **validation** split, I am able to reproduce the same (or better) performance than that reported in the paper, using the provided weights and our weights trained from scratch using the same config `semseg-pt-v3m1-0-base`. Evaluation is done using `python -m nuscenes.eval.lidarseg.evaluate` instead of the provided `test.sh`.
> 
> mIoU
> Paper (Tab. 7)	80.4
> Provided ckpt	80.3
> Ours (v1.5.1)	81.1
> Ours (latest)	81.0
> On the **test** split, however, I am not able to get the `82.7` mAP as reported in the paper. Worryingly, the model trained by us seems to have degraded performance (-1%), which is abnormal compared to other approaches where the test set mAP is typically higher than validation.
> 
> mIoU
> Paper (Tab. 7)	82. 7
> Provided ckpt	81.2
> Ours (v1.5.1)	80.8
> Ours (latest)	80.3
> The nuScenes dataset is freshly downloaded and the provided info pickle files are used. The inference is done exactly the same as the validation split, except the `split` is changed to `test` in the config. I am using the `python -m nuscenes.eval.lidarseg.validate_submission` command to validate and generate the submission zip file.
> 
> I am not too familiar with the nuScenes semantic segmentation challenge submission process. I am wondering if there is anything that I might have missed in the inference or submission process that could result in this degradation in performance. I would appreciate any help and clarifications. Thank you!

Hi there! I want to ask how to get test mIoU on nuScenes?

**Comment by Gofinge** [comment]
Hi, I think our test script will automatically save something ready for submission to the official benchmark. (https://github.com/Pointcept/Pointcept/blob/main/pointcept/engines/test.py#L145)
