### ISSUE TITLE
Backward issue in pointops.KNNQuery

### ISSUE THREAD

**Issue by yuantianyuan01** [Pointcept/Pointcept#343]
Thank you for this helpful codebase! I'm trying to use PointTransformer models (currently PTv1) in my project but I get errors when backpropogating the gradient: 
```
.../python3.10/site-packages/torch/autograd/function.py", line 406, in backward
    raise NotImplementedError(
NotImplementedError: You must implement either the backward or vjp method for your custom autograd.Function to use it with backward mode AD.
```
I find the error is reported on pointops.knn_query function, and I find the `class KNNQuery(Function)` does not implement `backward` function ([here](https://github.com/Pointcept/Pointcept/blob/main/libs/pointops/functions/query.py#L7)). I'm not very familiar with torch.autograd.Function so I'm wondering 1) is it the root of this error? Why is the backward function not implemented? And 2) how can I fix it?

**Comment by Gofinge** [comment]
Yes, knn don’t need to backward, maybe add with torch.no_grad() to cover and can solve this issue. (You definitely should use v3 or v2 which are significantly faster and stronger)

**Comment by yuantianyuan01** [comment]
Thanks for your quick reply! I'll try v2 later. I just don't know why no one seems to encountered this issue. The error persists even I wrapped the function with torch.no_grad() and only solved after I add a dummy backward function like:
```
class KNNQuery(Function):
    @staticmethod
    def forward(ctx, nsample, xyz, offset, new_xyz=None, new_offset=None):
        """
        input: coords: (n, 3), new_xyz: (m, 3), offset: (b), new_offset: (b)
        output: idx: (m, nsample) -1 is placeholder, dist2: (m, nsample)
        """
        if new_xyz is None or new_offset is None:
            new_xyz = xyz
            new_offset = offset
        assert xyz.is_contiguous() and new_xyz.is_contiguous()
        m = new_xyz.shape[0]
        idx = torch.cuda.IntTensor(m, nsample).zero_()
        dist2 = torch.cuda.FloatTensor(m, nsample).zero_()
        knn_query_cuda(
            m, nsample, xyz, new_xyz, offset.int(), new_offset.int(), idx, dist2
        )
        return idx, torch.sqrt(dist2)
    
    @staticmethod
    def backward(ctx, idx, dist2):
        # no gradient
        return (None, None, None, None, None)
```
I suppose we do not need any gradient on the `idx` result?

**Comment by Gofinge** [comment]
No need gradient for fix result.

**Comment by yuantianyuan01** [comment]
Thanks.
