### ISSUE TITLE
Video memory overflow issue

### ISSUE THREAD

**Issue by jtj01** [Pointcept/Pointcept#344]
Hello author, I have downloaded the code from your GitHub and provided the s3dis processed dataset
![image-20241029174724916](https://github.com/user-attachments/assets/48894e0c-d941-451a-9483-eb52acc632fd)
Then download the pre trained model providedmodel_best.pth

CUDA_VISIBLE_DEVICES=0,1,2,3 python tools/test.py --config-file configs/s3dis/semseg-pt-v3m1-1-rpe.py --options save_path=exp/s3dis/semseg-pt-v3m1-1-rpe weight=model/s3dis-semseg-pt-v3m1-0-rpe/model_best.pth

I encountered the following error that caused a burst of memory. I changed the batch size in 'Pointcept/config/s3dis/semseg-pt-v3m1-1-rpe. py' from 12 to 6, but it still has the same error. My computer configuration is 4 * RTX 3090.I am very confused. How can I solve it?

**Comment by jtj01** [comment]
export PYTHONPATH=./
python tools/test.py \
 --config-file configs/s3dis/semseg-pt-v3m1-1-rpe.py \
 --num-gpus 4 \
 --options save_path=exp/s3dis/semseg-pt-v3m1-1-rpe weight=model/s3dis-semseg-pt-v3m1-0-rpe/model_best.pth

Running like this still reports the same error

**Comment by jtj01** [comment]
Follow up: I successfully ran it on two A100s!
But! The data that ran out seems a bit inaccurate

I interpreted the data format of the. npy file as follows：

Coords shape: (1047554,)
Coords contents: [ 1  2  2  4 11]

Causing me to be unable to visualize it.I sincerely hope that the author can help me answer this question！

**Comment by Gofinge** [comment]
Hi, sorry for the late response, I just recovered from the busy schedule for the CVPR project. 

> I encountered the following error that caused a burst of memory.

May I ask which error you encountered?

**Comment by jtj01** [comment]
> 你好，抱歉回复晚了，我刚刚从 CVPR 项目的繁忙日程中恢复过来。
> 
> > 我遇到了以下导致内存爆发的错误。
> 
> 请问您遇到的是哪一个错误？

非常感谢，我已经解决了
