### ISSUE TITLE
Bad result

### ISSUE THREAD

**Issue by alphabet-lgtm** [Pointcept/Pointcept#346]
I achieved a low mIoU of only 0.1985 when testing on the ScanNet dataset.

Here's the test command I used:

PYTHONPATH=. python tools/test.py --config-file configs/scannet/semseg-pt-v3m1-0-base.py --options save_path=exp/scannet/semseg-pt-v3m1-0-base/ weight=checkpoints/scannet.pth
I obtained the weights from this link: [PointTransformerV3 on Hugging Face](https://huggingface.co/Pointcept/PointTransformerV3/tree/main/scannet-semseg-pt-v3m1-0-base).

Do you have any suggestions on why the mIoU might be so low? Any advice would be greatly appreciated!

Best regards!

![image](https://github.com/user-attachments/assets/e78cd2ca-cff8-4833-a440-30c856c1c234)

**Comment by alphabet-lgtm** [comment]
Okay, I found it https://github.com/Pointcept/Pointcept/issues/284#issuecomment-2188177675. v1.5.1 worked

**Comment by Gofinge** [comment]
Hi, sorry for the late response, I just recovered from the busy schedule for the CVPR project. We will soon have a big update on the code and pre-trained model weight.
