### ISSUE TITLE
A small question about the attention data format

### ISSUE THREAD

**Issue by OuYaozhong** [Pointcept/Pointcept#352]
Hi, Pointcept Team,

I have a small question about the attention.

I notice that, in the implementation of Point Transformer V3, you have half the data format of QKV uniform tensor before feed them into the flash attention.  [here](https://github.com/Pointcept/Pointcept/blob/c4363c86e1e77325645d44bc8052b338031f1b30/pointcept/models/point_transformer_v3/point_transformer_v3m1_base.py#L208-L214)
```
feat = flash_attn.flash_attn_varlen_qkvpacked_func(
            qkv.half().reshape(-1, 3, H, C // H),
            cu_seqlens,
            max_seqlen=self.patch_size,
            dropout_p=self.attn_drop if self.training else 0,
            softmax_scale=self.scale,
).reshape(-1, C)
```

After that, you transfer the data format of result back into the original one. [here](https://github.com/Pointcept/Pointcept/blob/c4363c86e1e77325645d44bc8052b338031f1b30/pointcept/models/point_transformer_v3/point_transformer_v3m1_base.py#L215)
```
feat = feat.to(qkv.dtype)
```

Although it is not a big problem, I still wonder what is the meaning and motivation of doing this ?

Since you have used the Flash Attention to accelerate the attention operation, with the AutoMixPrecision mechanism, further force to half the data format of `qkv` can make a big influence on the training / inference speed based on the already existed acceleration means?

Or do you actually have other considerations for this operation ?

**Comment by Gofinge** [comment]
I remember that FlashAttention only accepts the Half precision, so we have to force it to half incase the input data is in other precision.
