### ISSUE TITLE
The difference implementation of RPE between Point Transformer V1/V2 and V3

### ISSUE THREAD

**Issue by OuYaozhong** [Pointcept/Pointcept#356]
Hi, Pointcept Team,

I notice that the RPE implementation is different between V1/V2 and V3.

### Background
----------------------------------
In Point Transformer V1, it simply follow the general strategy, directly add the position relation features, which go through a linear layer, into the `qk` vector, to plus in some relative position information into the features.
[relative code](https://github.com/Pointcept/Pointcept/blob/c4363c86e1e77325645d44bc8052b338031f1b30/pointcept/models/point_transformer/point_transformer_seg.py#L61-L69)
```
p_r, x_k = x_k[:, :, 0:3], x_k[:, :, 3:]
p_r = self.linear_p(p_r)
r_qk = (
    x_k
    - x_q.unsqueeze(1)
    + einops.reduce(
        p_r, "n ns (i j) -> n ns j", reduction="sum", j=self.mid_planes
    )
)
```

----------------------------------
In Point Transformer V2, you propose the position encoding multiplier, which in detail, is use linear layer generate the coefficient and the bias, than multiply and add to the `qk` features.
[relative code](https://github.com/Pointcept/Pointcept/blob/c4363c86e1e77325645d44bc8052b338031f1b30/pointcept/models/point_transformer_v2/point_transformer_v2m1_origin.py#L151-L157)
```
if self.pe_multiplier:
    pem = self.linear_p_multiplier(pos)
    relation_qk = relation_qk * pem
if self.pe_bias:
    peb = self.linear_p_bias(pos)
    relation_qk = relation_qk + peb
    value = value + peb
```

----------------------------------
However, in Point Transformer V3, you use a different strategy, though it still call `RPE`.
In detail,,
1. you define a `torch.nn.Parameters` variable named `rpe_table`, the shape of which is `[3 * self.rpe_num, num_heads]`.
2. the output of `RPE` depends on the `idx` of the grid that point located in. The `idx` as an index to select the corresponding `rep_table` item, or in other words, scatter the `rpe_table` item / trainable parameters into a same shape tensor based on the `idx`.

[relative code](https://github.com/Pointcept/Pointcept/blob/c4363c86e1e77325645d44bc8052b338031f1b30/pointcept/models/point_transformer_v3/point_transformer_v3m1_base.py#L29-L48)
```
class RPE(torch.nn.Module):
    def __init__(self, patch_size, num_heads):
        super().__init__()
        self.patch_size = patch_size
        self.num_heads = num_heads
        self.pos_bnd = int((4 * patch_size) ** (1 / 3) * 2)
        self.rpe_num = 2 * self.pos_bnd + 1
        self.rpe_table = torch.nn.Parameter(torch.zeros(3 * self.rpe_num, num_heads))
        torch.nn.init.trunc_normal_(self.rpe_table, std=0.02)

    def forward(self, coord):
        idx = (
            coord.clamp(-self.pos_bnd, self.pos_bnd)  # clamp into bnd
            + self.pos_bnd  # relative position to positive index
            + torch.arange(3, device=coord.device) * self.rpe_num  # x, y, z stride
        )
        out = self.rpe_table.index_select(0, idx.reshape(-1))
        out = out.view(idx.shape + (-1,)).sum(3)
        out = out.permute(0, 3, 1, 2)  # (N, K, K, H) -> (N, H, K, K)
        return out
```
  

### Question
If my understanding above is correct, although the strategy used in PTv3 is still reasonable, since I seems strange to some extent, I want to know, why you use another implementation of RPE in the PTv3?

**Comment by Gofinge** [comment]
I think RPE is not officially acknowledged as one component of PTv3 as we encourage CPE with sparse convolution. Yet for your mentioned RPE in PTv3 code, this is a way of RPE with a lookup embedding table that was also used in Stratified Transformer. I remember this way is easier to converge.
