### ISSUE TITLE
Reproducing the result on scannet200 of MSC

### ISSUE THREAD

**Issue by LydJason** [Pointcept/Pointcept#360]
Thank you for your excellent work! 

It seems that the README section for MSC only includes the guide to reproduce results on ScanNet20:
https://github.com/Pointcept/Pointcept/blob/c4363c86e1e77325645d44bc8052b338031f1b30/README.md?plain=1#L835-L848

How can I reproduce the results on ScanNet200 according to the paper?

It appears that there isn't a config file under configs/scannet200 that starts with "pretrain". Should I directly use the pretrained weights from ScanNet20 and fine-tune it on ScanNet200? If so, it seems that the input_channel of SPUNet under configs/scannet200 is set to 9, while it is set to 6 under configs/scannet, which prevents direct use of a model pre-trained on ScanNet20 for fine-tuning on ScanNet200.
https://github.com/Pointcept/Pointcept/blob/c4363c86e1e77325645d44bc8052b338031f1b30/configs/scannet200/semseg-spunet-v1m1-0-base.py#L18-L19
https://github.com/Pointcept/Pointcept/blob/c4363c86e1e77325645d44bc8052b338031f1b30/configs/scannet/semseg-spunet-v1m1-4-ft.py#L14-L15

Alternatively, should I modify the pretrain config of scannet20 (configs/scannet/pretrain-msc-v1m1-0-spunet-base.py) to support ScanNet200 pretraining?

Please let me know if I am mistaken or how to resolve this issue. Thank you again!

**Comment by LydJason** [comment]
@Gofinge If you can see this, thank you very much!

**Comment by Gofinge** [comment]
Hi, sorry for the late response, I just recovered from the busy schedule for the CVPR project. 

Yes, I usually copy the config for ScanNet20 to ScanNet200 and then compare the copied config with the ScanNet200 default config to adapt it to ScanNet200. I think only need to change the num_classes to 200 and the dataset type.

**Comment by LydJason** [comment]
Thank you for your response, It is of great help to me! I think this means that for the ScanNet20 and ScanNet200 datasets, I need to pretrain and finetune separately to replicate the results of MSC, rather than using the same pretrained weights from ScanNet20, is that correct?

I am a bit confused about this because I read another CVPR24 paper you were involved in, which is a follow-up to MSC, titled _"GroupContrast: Semantic-aware Self-supervised Representation Learning for 3D Understanding"_. In its experimental section, it references MSC's data and mentions that “For in-domain transfer learning where pre-training and finetuning are both conducted on the ScanNet dataset”. Additionally, the S3DIS experiments were also pretrained on ScanNet and finetuned on S3DIS.

This makes me a bit confused about whether these settings should involve separate pretraining or if a same scannet20 pretrained model should be used. 

I’m not sure if there is a misunderstanding on my part. I understand that these works might be from some time ago, I would greatly appreciate it if you could help me out with these relevant details. Please correct me if my understanding is incorrect. Thank you very much! @Gofinge

**Comment by Gofinge** [comment]
> rather than using the same pretrained weights from ScanNet20, is that correct?

Same pre-training weight for both ScanNet20 and ScanNet200 as well as any other benchmark.

PS: we will soon have a super powerful self-supervised learned PTv3 with ScanNet, ScanNet++, S3DIS, Structured3D, HM3D, ArkitScene etc. Wait for one month, I will make the code and paper available. I think it would be better to follow that one.

**Comment by LydJason** [comment]
That's great, thank you very much!

**Comment by RayYoh** [comment]
> > rather than using the same pretrained weights from ScanNet20, is that correct?
> 
> Same pre-training weight for both ScanNet20 and ScanNet200 as well as any other benchmark.
> 
> PS: we will soon have a super powerful self-supervised learned PTv3 with ScanNet, ScanNet++, S3DIS, Structured3D, HM3D, ArkitScene etc. Wait for one month, I will make the code and paper available. I think it would be better to follow that one.

Hi, Xiaoyang.
Very interested in 3D self-supervised representation learning and very curious about your novel method. Does this powerful method use the same architecture as PPT and scale to more datasets, or is it a totally different self-supervised method?
