### ISSUE TITLE
How does caching work ?

### ISSUE THREAD

**Issue by SpeedyGonzales949** [Pointcept/Pointcept#374]
Right now, I want to train PPT + PTv3 on Matterport. However it keeps crashing due to cuda insufficient memory. When I looked at the gpu memory usage, i notice one is subtantially higher. Why is this the case ?  Is it because of caching ? 
![image](https://github.com/user-attachments/assets/96fb57c4-5eaf-4611-be54-738a848a3f70)

Now I am running an experiment without caching, so far so good.  I also use a batch size of (2 per each GPU).  However batch time is 40% higher. So I would definitely like to continue to use caching. 

Update: experiment with batch size = 4 (2 per gpu) crashed, due to insufficient memory.

**Comment by Gofinge** [comment]
Yeah, I have the same problem. The Matterport Dataset has some very strange data that causes this issue, so I gave up using it. I hope you can also detect which data causes such an OOM, and you can also consider utilizing HM3D, for which I will release the preprocessing code soon.

**Comment by SpeedyGonzales949** [comment]
I see. I am excied for HM3D. Yes, which data causes OOM can be easily done, e.g. Collect name key and then simply print.
