### ISSUE TITLE
Can I replace PointGroup's backbone with PTv2 instead of SpUnet?

### ISSUE THREAD

**Issue by Lizhinwafu** [Pointcept/Pointcept#40]
Can I replace PointGroup's backbone with PTv2 instead of SpUnet?

**Comment by Gofinge** [comment]
Yes, of course. But I have not test it and it would be helpful if you can share your config.

**Comment by Gofinge** [comment]
I was because our framework adopts eval_epoch as the actual epoch num. If eval_epoch is 100 and epoch is 3000, then the dataset will loop 30 times. The error seems to be because of another reason.

**Comment by Gofinge** [comment]
Aha, recently I updated S3DIS preprocessing which can produce additional normal vectors for the dataset. You can re-preprocess S3DIS or directly download the processed one shared by us. Further please refer [here](https://github.com/Pointcept/Pointcept#s3dis). (Also, you can modify the config, and do not apply normal as a part of feat.)

**Comment by Gofinge** [comment]
Pointcept is in a phase of rapid evolution, please feel free to ask me any questions encountered.

**Comment by Gofinge** [comment]
Hi, I haven't written a test process for instance segmentation, and the test dataset config is None currently,  https://github.com/Pointcept/Pointcept/blob/main/configs/s3dis/insseg-pointgroup-v1m1-0-spunet-base.py#L120. You can directly use the evaluated result during training, and it is precise.

**Comment by Gofinge** [comment]
You can modify code [here](https://github.com/Pointcept/Pointcept/blob/main/pointcept/engines/hooks/evaluator.py#L445:L456) (pointcept.engine.hook.evaluator.InsSegEvaluator).

**Comment by Gofinge** [comment]
Hi, I mainly refer to the CSC code: https://github.com/facebookresearch/ContrastiveSceneContexts/blob/83515bef4754b3d90fc3b3a437fa939e0e861af8/downstream/insseg/lib/test.py#L113. The performance looked good and I didn't make a comparison of the two settings.

**Comment by Gofinge** [comment]
I tried the setting on normal ScanNet20 and S3DIS benchmarks and the performance was pretty good. I will run again and check the performance, please wait for my response. And could you share your custom config with me?

**Comment by Gofinge** [comment]
I checked the data and config you sent to me, I think it was because of data imbalance and difficulty imbalance. 1. You can first try to ignore _branch_ class instance and check the performance of _boll_ class; 2. Then, try to set different loss weights for the two classes.

**Comment by Gofinge** [comment]
Try this, change _boll_ index to 1, and change _branch_ index to 1, then ignore segment index 0. If it works, it means some hard code that ignores segment 0 exists in the evaluation code (The evaluation code is modified from ScanNet official, some hard code exists).

**Comment by Gofinge** [comment]
Yes, and I am not familiar with PointGroup, some hyperparameters,s and fitting mechanism might also lead to the result.
