### ISSUE TITLE
How to implement global attention in PointCept? 

### ISSUE THREAD

**Issue by linhaojia13** [Pointcept/Pointcept#47]
As explained in the ReadMe, PointCept consolidates the batch_size dimension and the num_point dimension when reading data, necessitating the use of an offset parameter to differentiate between different point cloud instances within the same batch. 

Therefore, if we were to compute global attention, we would need to use the offset to distinguish between different point cloud instances in a batch when implementing the multiplication of the query and key matrices. However, as far as I'm aware, Pointcept does not offer such an operator. 

I noticed that SPFormer faced the same issue. Their [solution](
https://github.com/sunjiahao1999/SPFormer/blob/89eeca8167a197a557e4ec6ef9d43168d4d4e1f0/spformer/model/query_decoder.py#L32) was to individually extract each point cloud from the batch data and calculate the global attention for each point cloud using a loop with the size equals to batch_size. Clearly, this serial method is not efficient. If I wish to implement an efficient  global attention operator in Pointcept, could you recommend any example code for reference?

**Comment by Gofinge** [comment]
Yes, of course, use PTv2 as an example, 
1. https://github.com/Pointcept/Pointcept/blob/main/pointcept/models/point_transformer_v2/point_transformer_v2m2_base.py#L207, make "referece_index" index to all points in the same point cloud instead of the neighborhood (need to assume all point cloud share a same shape);
2. Or just reshape the coord, feat to [b, n, c] as 2D attention (Also need to assume all point cloud share the same shape, more efficient for Multi-head Scalar Attention)

**Comment by linhaojia13** [comment]
Thank you very much for your guidance! Your first solution seems more feasible, and I plan to start experimenting along these lines.

However, while the second solution may seem simple, it appears to be less applicable in practice: from my understanding, the number of point clouds in Pointcept is variable (unless they exceed point_max). Therefore, the assumption that "all point clouds share the same shape" may not hold true in Pointcept. Do you have any simple ideas to make each point cloud have the same number of points?

**Comment by Gofinge** [comment]
Maybe you can add a Padding augmentation in Transformer and use it with SphereCrop (limit max point number). And usually for dataset like ModelNet, the number of points for each point cloud is the same, you can assume all point clouds share the same shape for a dataset like that.

**Comment by linhaojia13** [comment]
OK, thank you very much!
