### ISSUE TITLE
Does the Swin3D in Pointcept achieve the results in paper？

### ISSUE THREAD

**Issue by linhaojia13** [Pointcept/Pointcept#49]
I am extremely grateful for the pretraining and finetuning code provided in PointCept, which Swin3D didn't offer. My question is, can we achieve the results reported in the Swin3D paper using the training code provided here? 

Additionally, I noticed that you've also integrated many excellent methods, such as the Ocformer backbone and the PointGroup model. Could you please add the reproduction results Pointcept for these methods to the README?

**Comment by Gofinge** [comment]
I am mainly responsible for my own paper, but thanks to your suggestions, I will gradually improve them, but you know it needs some time to do this. According to Swin3D, I currently just make sure the setting is aligned and the code is runnable, I will share preprocessed Structured3D later today. Usually, you can trust the performance of Pointcept, I will provide a higher performance.

**Comment by linhaojia13** [comment]
Thank you very much! Your efforts will benefit the entire community!
