### ISSUE TITLE
S3DIS for STv1m1

### ISSUE THREAD

**Issue by EricLina** [Pointcept/Pointcept#5]
Is there a config to train STv1m1(Stratified Transformer) on S3DIS?

**Comment by Gofinge** [comment]
You can try to write one by yourself. Here is my usual steps:
1. Copy Semseg-PT-v2m2-base as Semseg-ST-v1m2-base
2. Replace the model config with Semseg-ST-v1m2-base in the ScanNet folder
3. Check input shape and output shape (e.g. ScanNet is 9 while S3DIS is 6)

**Comment by EricLina** [comment]
thanks.
