### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by shenggebiya** [Pointcept/Pointcept#50]
Thanks for your work, how to visualize the .npy and .label generated after testing, the .npy file seems to be one-dimensional
![image](https://github.com/Pointcept/Pointcept/assets/42925030/76dc99cd-5882-4f5f-b7ea-e2dec05bfdbb)

**Comment by Gofinge** [comment]
Hi, you can define a color map and map the prediction index to color. The visualization tool is in `pointcept.utils.visualization `(`save_point_could`) and you can export point cloud to `.ply` file as follow:
```
save_point_could(coord, color/255, save_path)
```

**Comment by shenggebiya** [comment]
Sorry, I'm a newbie, you can give the sample code for the generated .npy and .label files converted to .ply files

**Comment by Gofinge** [comment]
This issue might be helpful (https://github.com/Gofinge/PointTransformerV2/issues/23).

**Comment by shenggebiya** [comment]
Thank you, your answer is very helpful to me,
