### ISSUE TITLE
corrupt of Area_5/office_35 in S3DIS dataset.

### ISSUE THREAD

**Issue by mrsempress** [Pointcept/Pointcept#54]
First of all, thank you for the preprocessing data set S3DIS, but the office_35 file in Area_5 is damaged. Can you upload the file of this scene again, as the origin dataset is so large? Thanks.

**Comment by Gofinge** [comment]
Hi, thanks for pointing out the issue. I tried to download the provided S3DIS data and load the office_35 in Area_5, but no collapsed data was found, could you help me recheck it?
![image](https://github.com/Pointcept/Pointcept/assets/39218229/6a7e760b-c21f-4522-96ea-018362e89ecc)

**Comment by mrsempress** [comment]
Sorry, all files can be downloaded normally after I re-downloaded. Thanks for your reply and work.
