### ISSUE TITLE
Why using subtraction based Vector Attention? 

### ISSUE THREAD

**Issue by EricLina** [Pointcept/Pointcept#6]
Point Transformer is a series of very advanced and excellent works, but I have some questions about the model structure that I need you to answer.

Whether it is V1 or V2, both use subtraction to obtain relation_qk. What are the benefits of doing this?Why does Point Transformer insist on using subtraction-based vector attention instead of the mainstream multiplication (QK^T)?

> relation_qk = key - query.unsqueeze(1)

Thanks.

**Comment by EricLina** [comment]
I've found part of the answer in your paper.
> vector attention, where the attention weights are vectors that can modulate the individual feature channels.
sorry, I should read your paper in detail.

**Comment by Gofinge** [comment]
`Whether it is V1 or V2, both use subtraction to obtain relation_qk. What are the benefits of doing this?`

There is something interesting about subtraction relations that we did not mention in our paper. For PTv1, there is not much difference between each relation encoding operator. While for PTv2, when we change the Query and Key projection operator for Linear Layer to Non-Linear Layer, the subtraction relation operator is better than other relation operators.

**Comment by EricLina** [comment]
Another Question: Given Q[N,c], K[N,c], and V[N,c], the complexity of vector attention (based on subtraction) is O(Nc), while the complexity of scalar attention (based on vector multiplication) is O(N^2c).Why don't we extend attention to all points instead of K local points?

**Comment by Gofinge** [comment]
The GPU memory will be out of limit and the 3D dataset is not large scale enough to support training global attention.

**Comment by EricLina** [comment]
> The GPU memory will be out of limit and the 3D dataset is not large scale enough to support training global attention.

I mean, Extende the sampling region from KNN to all point.

**Comment by Gofinge** [comment]
Extending the sampling region from KNN to all points meaning operate global attention, while attention among all points requires a huge cost of memory.
