### ISSUE TITLE
Cannot reproduce results from semantic_kitti PTv2 pretrained model

### ISSUE THREAD

**Issue by antao97** [Pointcept/Pointcept#64]
Hi, I download your pretrained model on semantic_kitti dataset from #42, but I cannot reproduce your results.

I use the following command to test the model:
```
python tools/test.py --config-file configs/semantic_kitti/semseg-pt-v2m2-0-base.py --options save_path=pretrained/sk-semseg-pt-v2m2-0-base weight=pretrained/sk-semseg-pt-v2m2-0-base/model/model_best.pth
```
The testing log is here:
[test-model_best.log](https://github.com/Pointcept/Pointcept/files/12210913/test-model_best.log)

**Comment by Gofinge** [comment]
As your opened issue #63 mentioned, your local environment has a strange training curve on ScanNet, and my suggestion is to ensure you can run Pointcept correctly before reproducing the testing result with our provided model weight.

**Comment by antao97** [comment]
See #63
