### ISSUE TITLE
scannet

### ISSUE THREAD

**Issue by FT-Zheng** [Pointcept/Pointcept#66]
Hello, I noticed that in the scannet benchmark submission, both the train and val datasets were used for training. In this case, how should we select the final test model? Should we use the last epoch or do we need to validate during training and save the model with the best validation performance?

**Comment by Gofinge** [comment]
Hi, just use the model last and pray for a good result. There is no need to evaluate on Val split. Consequently, I turn off evaluation for submit mod.

**Comment by FT-Zheng** [comment]
Thank you very much.
