### ISSUE TITLE
Test results on the benchmark

### ISSUE THREAD

**Issue by wuxiaolang** [Pointcept/Pointcept#68]
You mentioned the instability of the ScanNet benchmark [here](https://github.com/Gofinge/PointTransformerV2/issues/34#issuecomment-1511456137). How did you attempt multiple trials? Did you submit the same zip file as the second submission? Or did you retrain and then submit again? Did you train for more epochs, such as greater than 900?

Thanks for your great work!

**Comment by Gofinge** [comment]
1. “ How did you attempt multiple trials?”
One chance per two weeks;

2. "Did you submit the same zip file as the second submission?"
Why waste a chance for the same submission?

3. "Did you retrain and then submit again?"
Yes, retrain for another weight.

4. "Did you train for more epochs?"
Always 900 epochs. This parameter does not matter so much.

**Comment by wuxiaolang** [comment]
Got it, thank you!
