### ISSUE TITLE
Problem when installing MinkowskiEngine in the pointcept environment

### ISSUE THREAD

**Issue by Pixie8888** [Pointcept/Pointcept#82]
Hi,
I installed pointcept environment (pytorch=1.12.1) following instruction. Now, I want to further install MinkowskiEngine in the pointcept  environment. I follow the instruction in Minkowski github page. When I install "conda install openblas-devel -c anaconda", it will always downgrade the pytorch to cpu version, and I can't build Minkowski because torch.cuda.is_available()=False. How to solve it?

![image](https://github.com/Pointcept/Pointcept/assets/72333326/0dda357b-68aa-4dd4-9687-342accfd3115)

**Comment by Gofinge** [comment]
Hi, it is a common issue for Mink installation. You can try the following options:
1. Install a lower version of PyTorch;
2. Install PyTorch with pip, instead of conda;
3. Open an issue in Mink repo.

**Comment by Pixie8888** [comment]
Thanks!
