### ISSUE TITLE
Scannet Preprocessing

### ISSUE THREAD

**Issue by Achleshwar** [Pointcept/Pointcept#98]
Thanks a lot for the great work!!
 I am trying to run the preprocessing code for data preparation of ScanNet. The function [compute_full_overlapping](https://github.com/Pointcept/Pointcept/blob/main/pointcept/datasets/preprocessing/scannet/scannet_pair/compute_full_overlapping.py#L51) seems to be running quite slow for me. I wanted to confirm how long does it take approximately to run on a scene (with say ~300 views). It took me 1.5 hours just for one such scene :grimacing:

**Comment by Gofinge** [comment]
For the usual task, you don't need to run "scannet_pair" preprocessing. The "scannet_pair" preprocessing was modified from the paper PointContrast (https://github.com/facebookresearch/PointContrast) and as we discussed in our paper MSC, it is time-consuming. You only need to run (pointcept/datasets/preprocessing/scannet/preprocess_scannet.py)

If you do want to reproduce PointContast, the preprocess does cost a lot of time. Please be patient to wait.

**Comment by Achleshwar** [comment]
I see, that helps. I agree, after reading the code in detail, I think I can get away with w/o using `compute_full_overlapping` for my task. Thank you for your detailed response! (closing this issue)
